// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class AktualnyStanMagazynu
{
    public int IdMaterial { get; set; }

    public string NazwaMaterialu { get; set; }

    public string OpisMaterialu { get; set; }

    public string RodzajMaterialu { get; set; }

    public decimal CalkowiteDostawy { get; set; }

    public decimal CalkowiteZuzycie { get; set; }

    public decimal? AktualnyStan { get; set; }
}