// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class Awaria
{
    public int IdAwaria { get; set; }

    public int IdMaszyna { get; set; }

    public DateOnly DataZgloszenia { get; set; }

    public int IdPracownik { get; set; }

    public string Opis { get; set; }

    public DateOnly? DataUsuniecia { get; set; }

    public virtual ICollection<CzesciAwaria> CzesciAwaria { get; set; } = new List<CzesciAwaria>();

    public virtual Maszyna IdMaszynaNavigation { get; set; }

    public virtual Pracownik IdPracownikNavigation { get; set; }
}