// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class BadanieMedyczne
{
    public int IdBadanieMedyczne { get; set; }

    public int IdPracownik { get; set; }

    public int IdTypBadaniaMed { get; set; }

    public DateOnly DataBadania { get; set; }

    public DateOnly? DataWaznosci { get; set; }

    public decimal Koszt { get; set; }

    public string Uwagi { get; set; }

    public virtual Pracownik IdPracownikNavigation { get; set; }

    public virtual TypBadaniaMed IdTypBadaniaMedNavigation { get; set; }
}