// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class CzesciPrzeglady
{
    public int IdCzesciPrzeglady { get; set; }

    public int? IdCzesci { get; set; }

    public int? IdObsluga { get; set; }

    public int Liczba { get; set; }

    public string Opis { get; set; }

    public virtual CzesciZamienne IdCzesciNavigation { get; set; }

    public virtual Obsluga IdObslugaNavigation { get; set; }
}