// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class CzesciZamienne
{
    public int IdCzesci { get; set; }

    public string Nazwa { get; set; }

    public virtual ICollection<CzesciAwaria> CzesciAwaria { get; set; } = new List<CzesciAwaria>();

    public virtual ICollection<CzesciPrzeglady> CzesciPrzeglady { get; set; } = new List<CzesciPrzeglady>();
}