// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class CzesciAwaria
{
    public int IdCzesciAwaria { get; set; }

    public int IdCzesci { get; set; }

    public int IdAwaria { get; set; }

    public int Liczba { get; set; }

    public virtual Awaria IdAwariaNavigation { get; set; }

    public virtual CzescZamienna IdCzesciNavigation { get; set; }
}