// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class Dostawa
{
    public int IdDostawa { get; set; }

    public int IdFirma { get; set; }

    public int IdPracownik { get; set; }

    public DateTime DataDostawy { get; set; }

    public virtual Firma IdFirmaNavigation { get; set; }

    public virtual Pracownik IdPracownikNavigation { get; set; }

    public virtual ICollection<SzczegolyDostawy> SzczegolyDostawy { get; set; } = new List<SzczegolyDostawy>();
}