// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class Firma
{
    public int IdFirma { get; set; }

    public string Nazwa { get; set; }

    public string Miejscowosc { get; set; }

    public string KodPocztowy { get; set; }

    public string Ulica { get; set; }

    public string Numer { get; set; }

    public string Nip { get; set; }

    public virtual ICollection<Dostawa> Dostawa { get; set; } = new List<Dostawa>();

    public virtual ICollection<Gwarancja> Gwarancja { get; set; } = new List<Gwarancja>();

    public virtual ICollection<KlientFirma> KlientFirma { get; set; } = new List<KlientFirma>();
}