// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class Gwarancja
{
    public int IdGwarancja { get; set; }

    public int IdMaszyna { get; set; }

    public int IdFirma { get; set; }

    public decimal CzasGwarancji { get; set; }

    public string Warunki { get; set; }

    public virtual Firma IdFirmaNavigation { get; set; }

    public virtual Maszyna IdMaszynaNavigation { get; set; }
}