// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class Jednostka
{
    public int IdJednostki { get; set; }

    public string NazwaJednostki { get; set; }

    public virtual ICollection<Wlasciwosc> Wlasciwosc { get; set; } = new List<Wlasciwosc>();
}