// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class Jednostki
{
    public int IdJednostki { get; set; }

    public string NazwaJednostki { get; set; }

    public virtual ICollection<Wlasciwosci> Wlasciwosci { get; set; } = new List<Wlasciwosci>();
}