// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class Klient
{
    public int IdKlient { get; set; }

    public int? IdOsoba { get; set; }

    public virtual Osoba IdOsobaNavigation { get; set; }

    public virtual ICollection<KlientFirma> KlientFirma { get; set; } = new List<KlientFirma>();

    public virtual ICollection<Zamowienie> Zamowienie { get; set; } = new List<Zamowienie>();
}