// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class KlientFirma
{
    public int IdKlientFirma { get; set; }

    public int? IdKlient { get; set; }

    public int? IdFirma { get; set; }

    public DateOnly DataPocz { get; set; }

    public DateOnly DataKoniec { get; set; }

    public virtual Firma IdFirmaNavigation { get; set; }

    public virtual Klient IdKlientNavigation { get; set; }
}