// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class KontrolaMat
{
    public int IdKontrolaMat { get; set; }

    public int IdPracownik { get; set; }

    public decimal? Rbh { get; set; }

    public bool Zatwierdzone { get; set; }

    public decimal? Odpady { get; set; }

    public int IdZadanieP { get; set; }

    public int IdMaterial { get; set; }

    public virtual Material IdMaterialNavigation { get; set; }

    public virtual Pracownik IdPracownikNavigation { get; set; }

    public virtual ZadanieProdukcyjne IdZadaniePNavigation { get; set; }

    public virtual ICollection<PomiarMat> PomiarMat { get; set; } = new List<PomiarMat>();
}