// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class MaszynaWyp
{
    public int IdMaszynaWyp { get; set; }

    public int IdNormaP { get; set; }

    public int IdMaszyna { get; set; }

    public int IdWyposazenie { get; set; }

    public virtual Maszyna IdMaszynaNavigation { get; set; }

    public virtual NormaProd IdNormaPNavigation { get; set; }

    public virtual Wyposazenie IdWyposazenieNavigation { get; set; }
}