// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class Maszyna
{
    public int IdMaszyna { get; set; }

    public string Nazwa { get; set; }

    public string Uwagi { get; set; }

    public DateOnly DataZakupu { get; set; }

    public DateOnly DataUruchomienia { get; set; }

    public DateOnly? DataWylaczenia { get; set; }

    public virtual ICollection<Awaria> Awaria { get; set; } = new List<Awaria>();

    public virtual ICollection<Gwarancja> Gwarancja { get; set; } = new List<Gwarancja>();

    public virtual ICollection<MaszynaTyp> MaszynaTyp { get; set; } = new List<MaszynaTyp>();

    public virtual ICollection<MaszynaWyp> MaszynaWyp { get; set; } = new List<MaszynaWyp>();

    public virtual ICollection<NormyMaszyna> NormyMaszyna { get; set; } = new List<NormyMaszyna>();

    public virtual ICollection<Obsluga> Obsluga { get; set; } = new List<Obsluga>();

    public virtual ICollection<ZadanieProdukcyjne> ZadanieProdukcyjne { get; set; } = new List<ZadanieProdukcyjne>();
}