// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class MaszynaTyp
{
    public int IdMaszynaTyp { get; set; }

    public int IdTyp { get; set; }

    public int IdMaszyna { get; set; }

    public virtual Maszyna IdMaszynaNavigation { get; set; }

    public virtual Typ IdTypNavigation { get; set; }
}