// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class Material
{
    public int IdMaterial { get; set; }

    public string Nazwa { get; set; }

    public string Opis { get; set; }

    public int IdRodzaj { get; set; }

    public virtual RodzajMaterialu IdRodzajNavigation { get; set; }

    public virtual ICollection<KontrolaMat> KontrolaMat { get; set; } = new List<KontrolaMat>();

    public virtual ICollection<MaterialWlasciwosci> MaterialWlasciwosci { get; set; } = new List<MaterialWlasciwosci>();

    public virtual ICollection<NormaProd> NormaProd { get; set; } = new List<NormaProd>();

    public virtual ICollection<SzczegolyDostawy> SzczegolyDostawy { get; set; } = new List<SzczegolyDostawy>();

    public virtual ICollection<SzczegolyZamowienia> SzczegolyZamowienia { get; set; } = new List<SzczegolyZamowienia>();
}