// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class NormaProd
{
    public int IdNormaP { get; set; }

    public int IdProdukt { get; set; }

    public int IdMaterial { get; set; }

    public decimal IloscMat { get; set; }

    public decimal Ilosc { get; set; }

    public decimal Czas { get; set; }

    public DateOnly Data { get; set; }

    public virtual Material IdMaterialNavigation { get; set; }

    public virtual Produkt IdProduktNavigation { get; set; }

    public virtual ICollection<MaszynaWyp> MaszynaWyp { get; set; } = new List<MaszynaWyp>();

    public virtual ICollection<Produkcja> Produkcja { get; set; } = new List<Produkcja>();
}