// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class Normy
{
    public int IdNormy { get; set; }

    public string Nazwa { get; set; }

    public string Opis { get; set; }

    public virtual ICollection<ProduktyNormy> ProduktyNormy { get; set; } = new List<ProduktyNormy>();
}