// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class NormyMaszyna
{
    public int IdNormyMaszyna { get; set; }

    public int IdNormyEkspl { get; set; }

    public int IdMaszyna { get; set; }

    public decimal Wartosc { get; set; }

    public virtual Maszyna IdMaszynaNavigation { get; set; }

    public virtual NormyEksploatacyjne IdNormyEksplNavigation { get; set; }
}