// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class NormyEksploatacyjne
{
    public int IdNormyEkspl { get; set; }

    public string NazwaNormy { get; set; }

    public decimal PrzebiegNorma { get; set; }

    public virtual ICollection<NormyMaszyna> NormyMaszyna { get; set; } = new List<NormyMaszyna>();
}