// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class Obsluga
{
    public int IdObsluga { get; set; }

    public int IdMaszyna { get; set; }

    public DateOnly DataPoczatek { get; set; }

    public int IdPracownik { get; set; }

    public int IdRodzajObslugi { get; set; }

    public string Uwagi { get; set; }

    public DateOnly? DataKoniec { get; set; }

    public decimal Przebieg { get; set; }

    public virtual ICollection<CzesciPrzeglady> CzesciPrzeglady { get; set; } = new List<CzesciPrzeglady>();

    public virtual Maszyna IdMaszynaNavigation { get; set; }

    public virtual Pracownik IdPracownikNavigation { get; set; }

    public virtual RodzajObslugi IdRodzajObslugiNavigation { get; set; }
}