// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class Osoba
{
    public int IdOsoba { get; set; }

    public string Imie { get; set; }

    public string Nazwisko { get; set; }

    public string NrTelefonu { get; set; }

    public string AdresEMail { get; set; }

    public string Miejscowosc { get; set; }

    public string KodPocztowy { get; set; }

    public string Ulica { get; set; }

    public string Numer { get; set; }

    public string Pesel { get; set; }

    public virtual ICollection<Klient> Klient { get; set; } = new List<Klient>();

    public virtual ICollection<Pracownik> Pracownik { get; set; } = new List<Pracownik>();
}