// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace PodkladexApp.Models;

public partial class PodkladexContext : DbContext
{
    public PodkladexContext()
    {
    }

    public PodkladexContext(DbContextOptions<PodkladexContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AktualnyStanMagazynu> AktualnyStanMagazynu { get; set; }

    public virtual DbSet<Awaria> Awaria { get; set; }

    public virtual DbSet<BadanieMedyczne> BadanieMedyczne { get; set; }

    public virtual DbSet<CzescZamienna> CzescZamienna { get; set; }

    public virtual DbSet<CzesciAwaria> CzesciAwaria { get; set; }

    public virtual DbSet<CzesciPrzeglady> CzesciPrzeglady { get; set; }

    public virtual DbSet<Dostawa> Dostawa { get; set; }

    public virtual DbSet<Firma> Firma { get; set; }

    public virtual DbSet<Gwarancja> Gwarancja { get; set; }

    public virtual DbSet<Jednostka> Jednostka { get; set; }

    public virtual DbSet<Klient> Klient { get; set; }

    public virtual DbSet<KlientFirma> KlientFirma { get; set; }

    public virtual DbSet<KontrolaMat> KontrolaMat { get; set; }

    public virtual DbSet<KontrolaProd> KontrolaProd { get; set; }

    public virtual DbSet<Maszyna> Maszyna { get; set; }

    public virtual DbSet<MaszynaTyp> MaszynaTyp { get; set; }

    public virtual DbSet<MaszynaWyp> MaszynaWyp { get; set; }

    public virtual DbSet<Material> Material { get; set; }

    public virtual DbSet<MaterialWlasciwosci> MaterialWlasciwosci { get; set; }

    public virtual DbSet<Norma> Norma { get; set; }

    public virtual DbSet<NormaProd> NormaProd { get; set; }

    public virtual DbSet<NormyEksploatacyjne> NormyEksploatacyjne { get; set; }

    public virtual DbSet<NormyMaszyna> NormyMaszyna { get; set; }

    public virtual DbSet<Obsluga> Obsluga { get; set; }

    public virtual DbSet<Osoba> Osoba { get; set; }

    public virtual DbSet<Pomiar> Pomiar { get; set; }

    public virtual DbSet<PomiarMat> PomiarMat { get; set; }

    public virtual DbSet<Pracownik> Pracownik { get; set; }

    public virtual DbSet<PracownikSzkolenia> PracownikSzkolenia { get; set; }

    public virtual DbSet<Produkcja> Produkcja { get; set; }

    public virtual DbSet<Produkt> Produkt { get; set; }

    public virtual DbSet<ProduktNorma> ProduktNorma { get; set; }

    public virtual DbSet<ProduktWlasciwosci> ProduktWlasciwosci { get; set; }

    public virtual DbSet<RodzajMaterialu> RodzajMaterialu { get; set; }

    public virtual DbSet<RodzajObslugi> RodzajObslugi { get; set; }

    public virtual DbSet<RodzajUmowy> RodzajUmowy { get; set; }

    public virtual DbSet<SiatkaPlac> SiatkaPlac { get; set; }

    public virtual DbSet<SzczegolyDostawy> SzczegolyDostawy { get; set; }

    public virtual DbSet<SzczegolyZamowienia> SzczegolyZamowienia { get; set; }

    public virtual DbSet<Szkolenie> Szkolenie { get; set; }

    public virtual DbSet<Typ> Typ { get; set; }

    public virtual DbSet<TypBadaniaMed> TypBadaniaMed { get; set; }

    public virtual DbSet<TypWlasciwosci> TypWlasciwosci { get; set; }

    public virtual DbSet<TypZwolnienia> TypZwolnienia { get; set; }

    public virtual DbSet<Umowa> Umowa { get; set; }

    public virtual DbSet<Urlop> Urlop { get; set; }

    public virtual DbSet<UrlopUmowa> UrlopUmowa { get; set; }

    public virtual DbSet<Wlasciwosc> Wlasciwosc { get; set; }

    public virtual DbSet<WniosekUrlopowy> WniosekUrlopowy { get; set; }

    public virtual DbSet<Wyposazenie> Wyposazenie { get; set; }

    public virtual DbSet<WyposazenieWlasciwosci> WyposazenieWlasciwosci { get; set; }

    public virtual DbSet<Wysylka> Wysylka { get; set; }

    public virtual DbSet<WysylkaZamowienie> WysylkaZamowienie { get; set; }

    public virtual DbSet<ZadanieProdukcyjne> ZadanieProdukcyjne { get; set; }

    public virtual DbSet<Zamowienie> Zamowienie { get; set; }

    public virtual DbSet<ZwolnienieLekarskie> ZwolnienieLekarskie { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=.\\MSSQLSERVER_KWZP;Initial Catalog=Podkladex;Persist Security Info=True; TrustServerCertificate=True; User ID=sa;Password=1qazXSW@");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AktualnyStanMagazynu>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("AktualnyStanMagazynu");

            entity.Property(e => e.AktualnyStan)
                .HasColumnType("decimal(38, 2)")
                .HasColumnName("Aktualny_Stan");
            entity.Property(e => e.CalkowiteDostawy)
                .HasColumnType("decimal(38, 2)")
                .HasColumnName("Calkowite_Dostawy");
            entity.Property(e => e.CalkowiteZuzycie)
                .HasColumnType("decimal(38, 15)")
                .HasColumnName("Calkowite_Zuzycie");
            entity.Property(e => e.IdMaterial).HasColumnName("ID_material");
            entity.Property(e => e.NazwaMaterialu)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("Nazwa_Materialu");
            entity.Property(e => e.OpisMaterialu)
                .HasMaxLength(50)
                .HasColumnName("Opis_Materialu");
            entity.Property(e => e.RodzajMaterialu)
                .HasMaxLength(50)
                .HasColumnName("Rodzaj_Materialu");
        });

        modelBuilder.Entity<Awaria>(entity =>
        {
            entity.HasKey(e => e.IdAwaria).HasName("PK__Awaria__8D4FCB83938A3855");

            entity.Property(e => e.IdAwaria).HasColumnName("ID_awaria");
            entity.Property(e => e.DataUsuniecia).HasColumnName("Data_usuniecia");
            entity.Property(e => e.DataZgloszenia).HasColumnName("Data_zgloszenia");
            entity.Property(e => e.IdMaszyna).HasColumnName("ID_maszyna");
            entity.Property(e => e.IdPracownik).HasColumnName("ID_pracownik");
            entity.Property(e => e.Opis)
                .IsRequired()
                .HasMaxLength(250);

            entity.HasOne(d => d.IdMaszynaNavigation).WithMany(p => p.Awaria)
                .HasForeignKey(d => d.IdMaszyna)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Awaria__ID_maszy__503BEA1C");

            entity.HasOne(d => d.IdPracownikNavigation).WithMany(p => p.Awaria)
                .HasForeignKey(d => d.IdPracownik)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Awaria__ID_praco__51300E55");
        });

        modelBuilder.Entity<BadanieMedyczne>(entity =>
        {
            entity.HasKey(e => e.IdBadanieMedyczne).HasName("PK__Badanie___D27847BA6EA5EF4C");

            entity.ToTable("Badanie_medyczne");

            entity.Property(e => e.IdBadanieMedyczne).HasColumnName("ID_badanie_medyczne");
            entity.Property(e => e.DataBadania).HasColumnName("Data_badania");
            entity.Property(e => e.DataWaznosci).HasColumnName("Data_waznosci");
            entity.Property(e => e.IdPracownik).HasColumnName("ID_pracownik");
            entity.Property(e => e.IdTypBadaniaMed).HasColumnName("ID_typ_badania_med");
            entity.Property(e => e.Koszt).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Uwagi).HasMaxLength(255);

            entity.HasOne(d => d.IdPracownikNavigation).WithMany(p => p.BadanieMedyczne)
                .HasForeignKey(d => d.IdPracownik)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Badanie_m__ID_pr__46E78A0C");

            entity.HasOne(d => d.IdTypBadaniaMedNavigation).WithMany(p => p.BadanieMedyczne)
                .HasForeignKey(d => d.IdTypBadaniaMed)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Badanie_m__ID_ty__47DBAE45");
        });

        modelBuilder.Entity<CzescZamienna>(entity =>
        {
            entity.HasKey(e => e.IdCzesci).HasName("PK__Czesc_za__3566F799A4C769B5");

            entity.ToTable("Czesc_zamienna");

            entity.Property(e => e.IdCzesci).HasColumnName("ID_czesci");
            entity.Property(e => e.Nazwa)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<CzesciAwaria>(entity =>
        {
            entity.HasKey(e => e.IdCzesciAwaria).HasName("PK__Czesci_a__2A11CA5C02B20A70");

            entity.ToTable("Czesci_awaria");

            entity.Property(e => e.IdCzesciAwaria).HasColumnName("ID_Czesci_awaria");
            entity.Property(e => e.IdAwaria).HasColumnName("ID_awaria");
            entity.Property(e => e.IdCzesci).HasColumnName("ID_czesci");

            entity.HasOne(d => d.IdAwariaNavigation).WithMany(p => p.CzesciAwaria)
                .HasForeignKey(d => d.IdAwaria)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Czesci_aw__ID_aw__55009F39");

            entity.HasOne(d => d.IdCzesciNavigation).WithMany(p => p.CzesciAwaria)
                .HasForeignKey(d => d.IdCzesci)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Czesci_aw__ID_cz__540C7B00");
        });

        modelBuilder.Entity<CzesciPrzeglady>(entity =>
        {
            entity.HasKey(e => e.IdCzesciPrzeglady).HasName("PK__Czesci_p__025E78FCE889F6C8");

            entity.ToTable("Czesci_przeglady");

            entity.Property(e => e.IdCzesciPrzeglady).HasColumnName("ID_Czesci_przeglady");
            entity.Property(e => e.IdCzesci).HasColumnName("ID_czesci");
            entity.Property(e => e.IdObsluga).HasColumnName("ID_obsluga");
            entity.Property(e => e.Opis).HasMaxLength(250);

            entity.HasOne(d => d.IdCzesciNavigation).WithMany(p => p.CzesciPrzeglady)
                .HasForeignKey(d => d.IdCzesci)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Czesci_pr__ID_cz__6442E2C9");

            entity.HasOne(d => d.IdObslugaNavigation).WithMany(p => p.CzesciPrzeglady)
                .HasForeignKey(d => d.IdObsluga)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Czesci_pr__ID_ob__65370702");
        });

        modelBuilder.Entity<Dostawa>(entity =>
        {
            entity.HasKey(e => e.IdDostawa).HasName("PK__Dostawa__6D633112CCAED5EC");

            entity.Property(e => e.IdDostawa).HasColumnName("ID_dostawa");
            entity.Property(e => e.DataDostawy).HasColumnName("Data_dostawy");
            entity.Property(e => e.IdFirma).HasColumnName("ID_firma");
            entity.Property(e => e.IdPracownik).HasColumnName("ID_pracownik");

            entity.HasOne(d => d.IdFirmaNavigation).WithMany(p => p.Dostawa)
                .HasForeignKey(d => d.IdFirma)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Dostawa__ID_firm__07C12930");

            entity.HasOne(d => d.IdPracownikNavigation).WithMany(p => p.Dostawa)
                .HasForeignKey(d => d.IdPracownik)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Dostawa__ID_prac__08B54D69");
        });

        modelBuilder.Entity<Firma>(entity =>
        {
            entity.HasKey(e => e.IdFirma).HasName("PK__Firma__30DD244A42D2523F");

            entity.HasIndex(e => e.Nip, "UQ__Firma__C7DEC3C6575706B2").IsUnique();

            entity.Property(e => e.IdFirma).HasColumnName("ID_firma");
            entity.Property(e => e.KodPocztowy)
                .HasMaxLength(10)
                .HasColumnName("Kod_pocztowy");
            entity.Property(e => e.Miejscowosc).HasMaxLength(50);
            entity.Property(e => e.Nazwa)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Nip)
                .IsRequired()
                .HasMaxLength(13)
                .IsUnicode(false)
                .HasColumnName("NIP");
            entity.Property(e => e.Numer).HasMaxLength(10);
            entity.Property(e => e.Ulica).HasMaxLength(50);
        });

        modelBuilder.Entity<Gwarancja>(entity =>
        {
            entity.HasKey(e => e.IdGwarancja).HasName("PK__Gwarancj__06520D2514394260");

            entity.Property(e => e.IdGwarancja).HasColumnName("ID_gwarancja");
            entity.Property(e => e.CzasGwarancji).HasColumnName("Czas_gwarancji");
            entity.Property(e => e.IdFirma).HasColumnName("ID_firma");
            entity.Property(e => e.IdMaszyna).HasColumnName("ID_maszyna");
            entity.Property(e => e.Warunki).HasMaxLength(250);

            entity.HasOne(d => d.IdFirmaNavigation).WithMany(p => p.Gwarancja)
                .HasForeignKey(d => d.IdFirma)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Gwarancja__ID_fi__4B7734FF");

            entity.HasOne(d => d.IdMaszynaNavigation).WithMany(p => p.Gwarancja)
                .HasForeignKey(d => d.IdMaszyna)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Gwarancja__ID_ma__4A8310C6");
        });

        modelBuilder.Entity<Jednostka>(entity =>
        {
            entity.HasKey(e => e.IdJednostki).HasName("PK__Jednostk__B50E042FC5DA54D2");

            entity.Property(e => e.IdJednostki).HasColumnName("ID_jednostki");
            entity.Property(e => e.NazwaJednostki)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("Nazwa_jednostki");
        });

        modelBuilder.Entity<Klient>(entity =>
        {
            entity.HasKey(e => e.IdKlient).HasName("PK__Klient__7382667E9436881E");

            entity.Property(e => e.IdKlient).HasColumnName("ID_klient");
            entity.Property(e => e.IdOsoba).HasColumnName("ID_osoba");

            entity.HasOne(d => d.IdOsobaNavigation).WithMany(p => p.Klient)
                .HasForeignKey(d => d.IdOsoba)
                .HasConstraintName("FK__Klient__ID_osoba__6383C8BA");
        });

        modelBuilder.Entity<KlientFirma>(entity =>
        {
            entity.HasKey(e => e.IdKlientFirma).HasName("PK__Klient_f__2AAE6DA709652C90");

            entity.ToTable("Klient_firma");

            entity.Property(e => e.IdKlientFirma).HasColumnName("ID_klient_firma");
            entity.Property(e => e.DataKoniec).HasColumnName("Data_koniec");
            entity.Property(e => e.DataPocz).HasColumnName("Data_pocz");
            entity.Property(e => e.IdFirma).HasColumnName("ID_firma");
            entity.Property(e => e.IdKlient).HasColumnName("ID_klient");

            entity.HasOne(d => d.IdFirmaNavigation).WithMany(p => p.KlientFirma)
                .HasForeignKey(d => d.IdFirma)
                .HasConstraintName("FK__Klient_fi__ID_fi__6754599E");

            entity.HasOne(d => d.IdKlientNavigation).WithMany(p => p.KlientFirma)
                .HasForeignKey(d => d.IdKlient)
                .HasConstraintName("FK__Klient_fi__ID_kl__66603565");
        });

        modelBuilder.Entity<KontrolaMat>(entity =>
        {
            entity.HasKey(e => e.IdKontrolaMat).HasName("PK__Kontrola__5856399FA23484CF");

            entity.ToTable("Kontrola_mat");

            entity.Property(e => e.IdKontrolaMat).HasColumnName("ID_Kontrola_mat");
            entity.Property(e => e.IdMaterial).HasColumnName("ID_material");
            entity.Property(e => e.IdPracownik).HasColumnName("ID_pracownik");
            entity.Property(e => e.IdZadanieP).HasColumnName("ID_zadanieP");
            entity.Property(e => e.Odpady).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Rbh)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("RBH");

            entity.HasOne(d => d.IdMaterialNavigation).WithMany(p => p.KontrolaMat)
                .HasForeignKey(d => d.IdMaterial)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Kontrola___ID_ma__29221CFB");

            entity.HasOne(d => d.IdPracownikNavigation).WithMany(p => p.KontrolaMat)
                .HasForeignKey(d => d.IdPracownik)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Kontrola___ID_pr__2739D489");

            entity.HasOne(d => d.IdZadaniePNavigation).WithMany(p => p.KontrolaMat)
                .HasForeignKey(d => d.IdZadanieP)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Kontrola___ID_za__282DF8C2");
        });

        modelBuilder.Entity<KontrolaProd>(entity =>
        {
            entity.HasKey(e => e.IdKontrolaProd).HasName("PK__Kontrola__3831EE896641EF19");

            entity.ToTable("Kontrola_prod");

            entity.Property(e => e.IdKontrolaProd).HasColumnName("ID_Kontrola_prod");
            entity.Property(e => e.IdPracownik).HasColumnName("ID_pracownik");
            entity.Property(e => e.IdZadanieP).HasColumnName("ID_zadanieP");
            entity.Property(e => e.Odpady).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Rbh)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("RBH");

            entity.HasOne(d => d.IdPracownikNavigation).WithMany(p => p.KontrolaProd)
                .HasForeignKey(d => d.IdPracownik)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Kontrola___ID_pr__2BFE89A6");

            entity.HasOne(d => d.IdZadaniePNavigation).WithMany(p => p.KontrolaProd)
                .HasForeignKey(d => d.IdZadanieP)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Kontrola___ID_za__2CF2ADDF");
        });

        modelBuilder.Entity<Maszyna>(entity =>
        {
            entity.HasKey(e => e.IdMaszyna).HasName("PK__Maszyna__38E0F77AB6E814AF");

            entity.Property(e => e.IdMaszyna).HasColumnName("ID_maszyna");
            entity.Property(e => e.DataUruchomienia).HasColumnName("Data_uruchomienia");
            entity.Property(e => e.DataWylaczenia).HasColumnName("Data_wylaczenia");
            entity.Property(e => e.DataZakupu).HasColumnName("Data_zakupu");
            entity.Property(e => e.Nazwa)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Uwagi).HasMaxLength(250);
        });

        modelBuilder.Entity<MaszynaTyp>(entity =>
        {
            entity.HasKey(e => e.IdMaszynaTyp).HasName("PK__Maszyna___EFC428C57ED6B8C9");

            entity.ToTable("Maszyna_typ");

            entity.Property(e => e.IdMaszynaTyp).HasColumnName("ID_maszyna_typ");
            entity.Property(e => e.IdMaszyna).HasColumnName("ID_maszyna");
            entity.Property(e => e.IdTyp).HasColumnName("ID_typ");

            entity.HasOne(d => d.IdMaszynaNavigation).WithMany(p => p.MaszynaTyp)
                .HasForeignKey(d => d.IdMaszyna)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Maszyna_t__ID_ma__3D2915A8");

            entity.HasOne(d => d.IdTypNavigation).WithMany(p => p.MaszynaTyp)
                .HasForeignKey(d => d.IdTyp)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Maszyna_t__ID_ty__3C34F16F");
        });

        modelBuilder.Entity<MaszynaWyp>(entity =>
        {
            entity.HasKey(e => e.IdMaszynaWyp).HasName("PK__Maszyna___EC15EAC359D4311D");

            entity.ToTable("Maszyna_wyp");

            entity.Property(e => e.IdMaszynaWyp).HasColumnName("ID_maszyna_wyp");
            entity.Property(e => e.IdMaszyna).HasColumnName("ID_maszyna");
            entity.Property(e => e.IdNormaP).HasColumnName("ID_normaP");
            entity.Property(e => e.IdWyposazenie).HasColumnName("ID_wyposazenie");

            entity.HasOne(d => d.IdMaszynaNavigation).WithMany(p => p.MaszynaWyp)
                .HasForeignKey(d => d.IdMaszyna)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Maszyna_w__ID_ma__46B27FE2");

            entity.HasOne(d => d.IdNormaPNavigation).WithMany(p => p.MaszynaWyp)
                .HasForeignKey(d => d.IdNormaP)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Maszyna_w__ID_no__45BE5BA9");

            entity.HasOne(d => d.IdWyposazenieNavigation).WithMany(p => p.MaszynaWyp)
                .HasForeignKey(d => d.IdWyposazenie)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Maszyna_w__ID_wy__47A6A41B");
        });

        modelBuilder.Entity<Material>(entity =>
        {
            entity.HasKey(e => e.IdMaterial).HasName("PK__Material__DF8526106A182DB2");

            entity.Property(e => e.IdMaterial).HasColumnName("ID_material");
            entity.Property(e => e.IdRodzaj).HasColumnName("ID_rodzaj");
            entity.Property(e => e.Nazwa)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Opis).HasMaxLength(50);

            entity.HasOne(d => d.IdRodzajNavigation).WithMany(p => p.Material)
                .HasForeignKey(d => d.IdRodzaj)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Material__ID_rod__01142BA1");
        });

        modelBuilder.Entity<MaterialWlasciwosci>(entity =>
        {
            entity.HasKey(e => e.IdMaterialWlasciwosci).HasName("PK__Material__6D0188719936BB62");

            entity.ToTable("Material_wlasciwosci");

            entity.Property(e => e.IdMaterialWlasciwosci).HasColumnName("ID_material_wlasciwosci");
            entity.Property(e => e.IdMaterial).HasColumnName("ID_material");
            entity.Property(e => e.IdWlasciwosci).HasColumnName("ID_wlasciwosci");
            entity.Property(e => e.WartoscMaksymalna)
                .HasColumnType("decimal(6, 2)")
                .HasColumnName("Wartosc_maksymalna");
            entity.Property(e => e.WartoscMinimalna)
                .HasColumnType("decimal(6, 2)")
                .HasColumnName("Wartosc_minimalna");
            entity.Property(e => e.WartoscNominalna)
                .HasColumnType("decimal(6, 2)")
                .HasColumnName("Wartosc_nominalna");

            entity.HasOne(d => d.IdMaterialNavigation).WithMany(p => p.MaterialWlasciwosci)
                .HasForeignKey(d => d.IdMaterial)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Material___ID_ma__04E4BC85");

            entity.HasOne(d => d.IdWlasciwosciNavigation).WithMany(p => p.MaterialWlasciwosci)
                .HasForeignKey(d => d.IdWlasciwosci)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Material___ID_wl__03F0984C");
        });

        modelBuilder.Entity<Norma>(entity =>
        {
            entity.HasKey(e => e.IdNormy).HasName("PK__Norma__E42B5C52A756DA03");

            entity.Property(e => e.IdNormy).HasColumnName("ID_normy");
            entity.Property(e => e.Nazwa)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Opis)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<NormaProd>(entity =>
        {
            entity.HasKey(e => e.IdNormaP).HasName("PK__Norma_pr__FD73E488791E116B");

            entity.ToTable("Norma_prod");

            entity.Property(e => e.IdNormaP).HasColumnName("ID_normaP");
            entity.Property(e => e.Czas).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Data).HasColumnName("Data_");
            entity.Property(e => e.IdMaterial).HasColumnName("ID_material");
            entity.Property(e => e.IdProdukt).HasColumnName("ID_produkt");
            entity.Property(e => e.Ilosc).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.IloscMat)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("Ilosc_mat");

            entity.HasOne(d => d.IdMaterialNavigation).WithMany(p => p.NormaProd)
                .HasForeignKey(d => d.IdMaterial)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Norma_pro__ID_ma__245D67DE");

            entity.HasOne(d => d.IdProduktNavigation).WithMany(p => p.NormaProd)
                .HasForeignKey(d => d.IdProdukt)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Norma_pro__ID_pr__236943A5");
        });

        modelBuilder.Entity<NormyEksploatacyjne>(entity =>
        {
            entity.HasKey(e => e.IdNormyEkspl).HasName("PK__Normy_ek__63D2F7FECC1EB172");

            entity.ToTable("Normy_eksploatacyjne");

            entity.Property(e => e.IdNormyEkspl).HasColumnName("ID_normy_ekspl");
            entity.Property(e => e.NazwaNormy)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("Nazwa_normy");
            entity.Property(e => e.PrzebiegNorma)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("Przebieg_norma");
        });

        modelBuilder.Entity<NormyMaszyna>(entity =>
        {
            entity.HasKey(e => e.IdNormyMaszyna).HasName("PK__Normy_ma__F353B32BD1583D20");

            entity.ToTable("Normy_maszyna");

            entity.Property(e => e.IdNormyMaszyna).HasColumnName("ID_Normy_maszyna");
            entity.Property(e => e.IdMaszyna).HasColumnName("ID_maszyna");
            entity.Property(e => e.IdNormyEkspl).HasColumnName("ID_normy_ekspl");
            entity.Property(e => e.Wartosc).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.IdMaszynaNavigation).WithMany(p => p.NormyMaszyna)
                .HasForeignKey(d => d.IdMaszyna)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Normy_mas__ID_ma__6166761E");

            entity.HasOne(d => d.IdNormyEksplNavigation).WithMany(p => p.NormyMaszyna)
                .HasForeignKey(d => d.IdNormyEkspl)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Normy_mas__ID_no__607251E5");
        });

        modelBuilder.Entity<Obsluga>(entity =>
        {
            entity.HasKey(e => e.IdObsluga).HasName("PK__Obsluga__5F5AD47642B95932");

            entity.Property(e => e.IdObsluga).HasColumnName("ID_obsluga");
            entity.Property(e => e.DataKoniec).HasColumnName("Data_koniec");
            entity.Property(e => e.DataPoczatek).HasColumnName("Data_poczatek");
            entity.Property(e => e.IdMaszyna).HasColumnName("ID_maszyna");
            entity.Property(e => e.IdPracownik).HasColumnName("ID_pracownik");
            entity.Property(e => e.IdRodzajObslugi).HasColumnName("ID_rodzaj_obslugi");
            entity.Property(e => e.Przebieg).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Uwagi).HasMaxLength(250);

            entity.HasOne(d => d.IdMaszynaNavigation).WithMany(p => p.Obsluga)
                .HasForeignKey(d => d.IdMaszyna)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Obsluga__ID_masz__59C55456");

            entity.HasOne(d => d.IdPracownikNavigation).WithMany(p => p.Obsluga)
                .HasForeignKey(d => d.IdPracownik)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Obsluga__ID_prac__5AB9788F");

            entity.HasOne(d => d.IdRodzajObslugiNavigation).WithMany(p => p.Obsluga)
                .HasForeignKey(d => d.IdRodzajObslugi)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Obsluga__ID_rodz__5BAD9CC8");
        });

        modelBuilder.Entity<Osoba>(entity =>
        {
            entity.HasKey(e => e.IdOsoba).HasName("PK__Osoba__7573A697B56A03C5");

            entity.HasIndex(e => e.Pesel, "UQ__Osoba__4F16EE7F0AA48120").IsUnique();

            entity.Property(e => e.IdOsoba).HasColumnName("ID_osoba");
            entity.Property(e => e.AdresEMail)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("Adres_e_mail");
            entity.Property(e => e.Imie)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.KodPocztowy)
                .HasMaxLength(10)
                .HasColumnName("Kod_pocztowy");
            entity.Property(e => e.Miejscowosc).HasMaxLength(50);
            entity.Property(e => e.Nazwisko)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.NrTelefonu)
                .IsRequired()
                .HasMaxLength(15)
                .HasColumnName("Nr_telefonu");
            entity.Property(e => e.Numer).HasMaxLength(10);
            entity.Property(e => e.Pesel)
                .HasMaxLength(11)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("PESEL");
            entity.Property(e => e.Ulica).HasMaxLength(50);
        });

        modelBuilder.Entity<Pomiar>(entity =>
        {
            entity.HasKey(e => e.IdPomiar).HasName("PK__Pomiar__D471E709945B8B12");

            entity.Property(e => e.IdPomiar).HasColumnName("ID_Pomiar");
            entity.Property(e => e.IdKontrolaProd).HasColumnName("ID_Kontrola_prod");
            entity.Property(e => e.IdWlasciwosci).HasColumnName("ID_wlasciwosci");
            entity.Property(e => e.WartoscZmierzona)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("Wartosc_zmierzona");

            entity.HasOne(d => d.IdKontrolaProdNavigation).WithMany(p => p.Pomiar)
                .HasForeignKey(d => d.IdKontrolaProd)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Pomiar__ID_Kontr__2FCF1A8A");

            entity.HasOne(d => d.IdWlasciwosciNavigation).WithMany(p => p.Pomiar)
                .HasForeignKey(d => d.IdWlasciwosci)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Pomiar__ID_wlasc__30C33EC3");
        });

        modelBuilder.Entity<PomiarMat>(entity =>
        {
            entity.HasKey(e => e.IdPomiarMat).HasName("PK__Pomiar_m__8465018056B2DC2F");

            entity.ToTable("Pomiar_mat");

            entity.Property(e => e.IdPomiarMat).HasColumnName("ID_Pomiar_mat");
            entity.Property(e => e.IdKontrolaMat).HasColumnName("ID_Kontrola_mat");
            entity.Property(e => e.IdWlasciwosci).HasColumnName("ID_wlasciwosci");
            entity.Property(e => e.WartoscZmierzona)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("Wartosc_zmierzona");

            entity.HasOne(d => d.IdKontrolaMatNavigation).WithMany(p => p.PomiarMat)
                .HasForeignKey(d => d.IdKontrolaMat)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Pomiar_ma__ID_Ko__339FAB6E");

            entity.HasOne(d => d.IdWlasciwosciNavigation).WithMany(p => p.PomiarMat)
                .HasForeignKey(d => d.IdWlasciwosci)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Pomiar_ma__ID_wl__3493CFA7");
        });

        modelBuilder.Entity<Pracownik>(entity =>
        {
            entity.HasKey(e => e.IdPracownik).HasName("PK__Pracowni__4AE49B6EDDCD24E4");

            entity.Property(e => e.IdPracownik).HasColumnName("ID_pracownik");
            entity.Property(e => e.IdOsoba).HasColumnName("ID_osoba");

            entity.HasOne(d => d.IdOsobaNavigation).WithMany(p => p.Pracownik)
                .HasForeignKey(d => d.IdOsoba)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Pracownik__ID_os__3A81B327");
        });

        modelBuilder.Entity<PracownikSzkolenia>(entity =>
        {
            entity.HasKey(e => e.IdPracownikSzkolenia).HasName("PK__Pracowni__C68FD1498B6DCF28");

            entity.ToTable("Pracownik_szkolenia");

            entity.Property(e => e.IdPracownikSzkolenia).HasColumnName("ID_pracownik_szkolenia");
            entity.Property(e => e.CenaSzkolenia)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("Cena_szkolenia");
            entity.Property(e => e.DataSzkolenia).HasColumnName("Data_szkolenia");
            entity.Property(e => e.DataWaznosci).HasColumnName("Data_waznosci");
            entity.Property(e => e.IdPracownik).HasColumnName("ID_pracownik");
            entity.Property(e => e.IdSzkolenia).HasColumnName("ID_szkolenia");

            entity.HasOne(d => d.IdPracownikNavigation).WithMany(p => p.PracownikSzkolenia)
                .HasForeignKey(d => d.IdPracownik)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Pracownik__ID_pr__4D94879B");

            entity.HasOne(d => d.IdSzkoleniaNavigation).WithMany(p => p.PracownikSzkolenia)
                .HasForeignKey(d => d.IdSzkolenia)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Pracownik__ID_sz__4E88ABD4");
        });

        modelBuilder.Entity<Produkcja>(entity =>
        {
            entity.HasKey(e => e.IdProdukcja).HasName("PK__Produkcj__69A3FC9937E036FB");

            entity.Property(e => e.IdProdukcja).HasColumnName("ID_produkcja");
            entity.Property(e => e.IdNormyP).HasColumnName("ID_normyP");
            entity.Property(e => e.IdPracownik).HasColumnName("ID_pracownik");
            entity.Property(e => e.IdZadanieP).HasColumnName("ID_zadanieP");
            entity.Property(e => e.Odpady).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Rbh)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("RBH");
            entity.Property(e => e.Wyprodukowano).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.IdNormyPNavigation).WithMany(p => p.Produkcja)
                .HasForeignKey(d => d.IdNormyP)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Produkcja__ID_no__395884C4");

            entity.HasOne(d => d.IdPracownikNavigation).WithMany(p => p.Produkcja)
                .HasForeignKey(d => d.IdPracownik)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Produkcja__ID_pr__37703C52");

            entity.HasOne(d => d.IdZadaniePNavigation).WithMany(p => p.Produkcja)
                .HasForeignKey(d => d.IdZadanieP)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Produkcja__ID_za__3864608B");
        });

        modelBuilder.Entity<Produkt>(entity =>
        {
            entity.HasKey(e => e.IdProdukt).HasName("PK__Produkt__FD71AB0D2041DD16");

            entity.Property(e => e.IdProdukt).HasColumnName("ID_produkt");
            entity.Property(e => e.Nazwa)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<ProduktNorma>(entity =>
        {
            entity.HasKey(e => e.IdProduktyNormy).HasName("PK__Produkt___4247AF0FC4116401");

            entity.ToTable("Produkt_Norma");

            entity.Property(e => e.IdProduktyNormy).HasColumnName("ID_produkty_normy");
            entity.Property(e => e.IdNormy).HasColumnName("ID_normy");
            entity.Property(e => e.IdProdukt).HasColumnName("ID_produkt");

            entity.HasOne(d => d.IdNormyNavigation).WithMany(p => p.ProduktNorma)
                .HasForeignKey(d => d.IdNormy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Produkt_N__ID_no__1BC821DD");

            entity.HasOne(d => d.IdProduktNavigation).WithMany(p => p.ProduktNorma)
                .HasForeignKey(d => d.IdProdukt)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Produkt_N__ID_pr__1CBC4616");
        });

        modelBuilder.Entity<ProduktWlasciwosci>(entity =>
        {
            entity.HasKey(e => e.IdProduktyWlasciwosci).HasName("PK__Produkt___AA8BF2340656D4C5");

            entity.ToTable("Produkt_wlasciwosci");

            entity.Property(e => e.IdProduktyWlasciwosci).HasColumnName("ID_produkty_wlasciwosci");
            entity.Property(e => e.IdProdukt).HasColumnName("ID_produkt");
            entity.Property(e => e.IdWlasciwosci).HasColumnName("ID_wlasciwosci");
            entity.Property(e => e.WartoscMaksymalna)
                .HasColumnType("decimal(6, 2)")
                .HasColumnName("Wartosc_maksymalna");
            entity.Property(e => e.WartoscMinimalna)
                .HasColumnType("decimal(6, 2)")
                .HasColumnName("Wartosc_minimalna");
            entity.Property(e => e.WartoscNominalna)
                .HasColumnType("decimal(6, 2)")
                .HasColumnName("Wartosc_nominalna");

            entity.HasOne(d => d.IdProduktNavigation).WithMany(p => p.ProduktWlasciwosci)
                .HasForeignKey(d => d.IdProdukt)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Produkt_w__ID_pr__208CD6FA");

            entity.HasOne(d => d.IdWlasciwosciNavigation).WithMany(p => p.ProduktWlasciwosci)
                .HasForeignKey(d => d.IdWlasciwosci)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Produkt_w__ID_wl__1F98B2C1");
        });

        modelBuilder.Entity<RodzajMaterialu>(entity =>
        {
            entity.HasKey(e => e.IdRodzaj).HasName("PK__Rodzaj_m__5605F872B261CFF1");

            entity.ToTable("Rodzaj_materialu");

            entity.Property(e => e.IdRodzaj).HasColumnName("ID_rodzaj");
            entity.Property(e => e.Nazwa)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<RodzajObslugi>(entity =>
        {
            entity.HasKey(e => e.IdRodzajObslugi).HasName("PK__Rodzaj_o__CCBEB0F8AF77B6E7");

            entity.ToTable("Rodzaj_obslugi");

            entity.Property(e => e.IdRodzajObslugi).HasColumnName("ID_rodzaj_obslugi");
            entity.Property(e => e.Nazwa)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Opis)
                .IsRequired()
                .HasMaxLength(250);
        });

        modelBuilder.Entity<RodzajUmowy>(entity =>
        {
            entity.HasKey(e => e.IdRodzaju).HasName("PK__Rodzaj_u__5001DC836944CCA0");

            entity.ToTable("Rodzaj_umowy");

            entity.Property(e => e.IdRodzaju).HasColumnName("ID_rodzaju");
            entity.Property(e => e.Nazwa)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Opis)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<SiatkaPlac>(entity =>
        {
            entity.HasKey(e => e.IdSiatkaPlac).HasName("PK__Siatka_p__487C8DBEB4EFD1F7");

            entity.ToTable("Siatka_plac");

            entity.Property(e => e.IdSiatkaPlac).HasColumnName("ID_siatka_plac");
            entity.Property(e => e.DataKoniec).HasColumnName("Data_koniec");
            entity.Property(e => e.DataPocz).HasColumnName("Data_pocz");
            entity.Property(e => e.IdPracownik).HasColumnName("ID_pracownik");
            entity.Property(e => e.Wynagrodzenie).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.IdPracownikNavigation).WithMany(p => p.SiatkaPlac)
                .HasForeignKey(d => d.IdPracownik)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Siatka_pl__ID_pr__4AB81AF0");
        });

        modelBuilder.Entity<SzczegolyDostawy>(entity =>
        {
            entity.HasKey(e => e.IdSzczegolyDostawy).HasName("PK__Szczegol__C5FC719BFF2422F6");

            entity.ToTable("Szczegoly_dostawy");

            entity.Property(e => e.IdSzczegolyDostawy).HasColumnName("ID_szczegoly_dostawy");
            entity.Property(e => e.Cena).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.IdDostawa).HasColumnName("ID_dostawa");
            entity.Property(e => e.IdMaterial).HasColumnName("ID_material");
            entity.Property(e => e.Liczba).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.IdDostawaNavigation).WithMany(p => p.SzczegolyDostawy)
                .HasForeignKey(d => d.IdDostawa)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Szczegoly__ID_do__0B91BA14");

            entity.HasOne(d => d.IdMaterialNavigation).WithMany(p => p.SzczegolyDostawy)
                .HasForeignKey(d => d.IdMaterial)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Szczegoly__ID_ma__0C85DE4D");
        });

        modelBuilder.Entity<SzczegolyZamowienia>(entity =>
        {
            entity.HasKey(e => e.IdSzczegolyZamowienia).HasName("PK__Szczegol__2D26C348E934B11C");

            entity.ToTable("Szczegoly_zamowienia");

            entity.Property(e => e.IdSzczegolyZamowienia).HasColumnName("ID_szczegoly_zamowienia");
            entity.Property(e => e.Cena).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.IdMaterial).HasColumnName("ID_material");
            entity.Property(e => e.IdProdukt).HasColumnName("ID_produkt");
            entity.Property(e => e.IdZamowienie).HasColumnName("ID_zamowienie");
            entity.Property(e => e.Ilosc).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Uwagi).HasMaxLength(255);

            entity.HasOne(d => d.IdMaterialNavigation).WithMany(p => p.SzczegolyZamowienia)
                .HasForeignKey(d => d.IdMaterial)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Szczegoly__ID_ma__114A936A");

            entity.HasOne(d => d.IdProduktNavigation).WithMany(p => p.SzczegolyZamowienia)
                .HasForeignKey(d => d.IdProdukt)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Szczegoly__ID_pr__10566F31");

            entity.HasOne(d => d.IdZamowienieNavigation).WithMany(p => p.SzczegolyZamowienia)
                .HasForeignKey(d => d.IdZamowienie)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Szczegoly__ID_za__0F624AF8");
        });

        modelBuilder.Entity<Szkolenie>(entity =>
        {
            entity.HasKey(e => e.IdSzkolenia).HasName("PK__Szkoleni__8655159D832D33B0");

            entity.Property(e => e.IdSzkolenia).HasColumnName("ID_szkolenia");
            entity.Property(e => e.CzyObowiazkowe).HasColumnName("Czy_obowiazkowe");
            entity.Property(e => e.Nazwa)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Opis).HasMaxLength(255);
        });

        modelBuilder.Entity<Typ>(entity =>
        {
            entity.HasKey(e => e.IdTyp).HasName("PK__Typ__1FBE66785D615373");

            entity.Property(e => e.IdTyp).HasColumnName("ID_typ");
            entity.Property(e => e.Nazwa)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<TypBadaniaMed>(entity =>
        {
            entity.HasKey(e => e.IdTypBadaniaMed).HasName("PK__Typ_bada__E8E973F3359C9AF5");

            entity.ToTable("Typ_badania_med");

            entity.Property(e => e.IdTypBadaniaMed).HasColumnName("ID_typ_badania_med");
            entity.Property(e => e.Nazwa)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Opis).HasMaxLength(255);
        });

        modelBuilder.Entity<TypWlasciwosci>(entity =>
        {
            entity.HasKey(e => e.IdTypWlasciwosci).HasName("PK__Typ_wlas__637DFEB760893728");

            entity.ToTable("Typ_wlasciwosci");

            entity.Property(e => e.IdTypWlasciwosci).HasColumnName("ID_typ_wlasciwosci");
            entity.Property(e => e.IdTyp).HasColumnName("ID_typ");
            entity.Property(e => e.IdWlasciwosci).HasColumnName("ID_wlasciwosci");
            entity.Property(e => e.Wartosc).HasColumnType("decimal(6, 2)");

            entity.HasOne(d => d.IdTypNavigation).WithMany(p => p.TypWlasciwosci)
                .HasForeignKey(d => d.IdTyp)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Typ_wlasc__ID_ty__7A672E12");

            entity.HasOne(d => d.IdWlasciwosciNavigation).WithMany(p => p.TypWlasciwosci)
                .HasForeignKey(d => d.IdWlasciwosci)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Typ_wlasc__ID_wl__797309D9");
        });

        modelBuilder.Entity<TypZwolnienia>(entity =>
        {
            entity.HasKey(e => e.IdTypZwolnienia).HasName("PK__Typ_zwol__3E156859FABC5A69");

            entity.ToTable("Typ_zwolnienia");

            entity.Property(e => e.IdTypZwolnienia).HasColumnName("ID_typ_zwolnienia");
            entity.Property(e => e.Nazwa)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Opis).HasMaxLength(255);
        });

        modelBuilder.Entity<Umowa>(entity =>
        {
            entity.HasKey(e => e.IdUmowa).HasName("PK__Umowa__D2EDF6FB02B20F3B");

            entity.Property(e => e.IdUmowa).HasColumnName("ID_umowa");
            entity.Property(e => e.DataRoz).HasColumnName("Data_roz");
            entity.Property(e => e.DataZak).HasColumnName("Data_zak");
            entity.Property(e => e.IdPracownik).HasColumnName("ID_pracownik");
            entity.Property(e => e.IdRodzaju).HasColumnName("ID_rodzaju");

            entity.HasOne(d => d.IdPracownikNavigation).WithMany(p => p.Umowa)
                .HasForeignKey(d => d.IdPracownik)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Umowa__ID_pracow__59063A47");

            entity.HasOne(d => d.IdRodzajuNavigation).WithMany(p => p.Umowa)
                .HasForeignKey(d => d.IdRodzaju)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Umowa__ID_rodzaj__59FA5E80");
        });

        modelBuilder.Entity<Urlop>(entity =>
        {
            entity.HasKey(e => e.IdUrlopu).HasName("PK__Urlop__595D2971BA4ADC48");

            entity.Property(e => e.IdUrlopu).HasColumnName("ID_urlopu");
            entity.Property(e => e.Nazwa)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<UrlopUmowa>(entity =>
        {
            entity.HasKey(e => e.IdUrlopUmowa).HasName("PK__Urlop_um__59C9C2FC692A95D7");

            entity.ToTable("Urlop_umowa");

            entity.Property(e => e.IdUrlopUmowa).HasColumnName("ID_Urlop_umowa");
            entity.Property(e => e.IdUmowy).HasColumnName("ID_umowy");
            entity.Property(e => e.IdUrlopu).HasColumnName("ID_urlopu");
            entity.Property(e => e.LiczbaDni)
                .HasColumnType("decimal(6, 2)")
                .HasColumnName("Liczba_dni");

            entity.HasOne(d => d.IdUmowyNavigation).WithMany(p => p.UrlopUmowa)
                .HasForeignKey(d => d.IdUmowy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Urlop_umo__ID_um__5CD6CB2B");

            entity.HasOne(d => d.IdUrlopuNavigation).WithMany(p => p.UrlopUmowa)
                .HasForeignKey(d => d.IdUrlopu)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Urlop_umo__ID_ur__5DCAEF64");
        });

        modelBuilder.Entity<Wlasciwosc>(entity =>
        {
            entity.HasKey(e => e.IdWlasciwosci).HasName("PK__Wlasciwo__BE19C14654AED16C");

            entity.Property(e => e.IdWlasciwosci).HasColumnName("ID_wlasciwosci");
            entity.Property(e => e.IdJednostki).HasColumnName("ID_jednostki");
            entity.Property(e => e.NazwaParametru)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("Nazwa_parametru");

            entity.HasOne(d => d.IdJednostkiNavigation).WithMany(p => p.Wlasciwosc)
                .HasForeignKey(d => d.IdJednostki)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Wlasciwos__ID_je__74AE54BC");
        });

        modelBuilder.Entity<WniosekUrlopowy>(entity =>
        {
            entity.HasKey(e => e.IdWniosku).HasName("PK__Wniosek___9D9F4BAF7704C019");

            entity.ToTable("Wniosek_urlopowy");

            entity.Property(e => e.IdWniosku).HasColumnName("ID_wniosku");
            entity.Property(e => e.DataRozp).HasColumnName("Data_rozp");
            entity.Property(e => e.DataZak).HasColumnName("Data_zak");
            entity.Property(e => e.IdPracownik).HasColumnName("ID_pracownik");
            entity.Property(e => e.IdUrlopu).HasColumnName("ID_urlopu");
            entity.Property(e => e.StatusWniosku).HasColumnName("Status_wniosku");

            entity.HasOne(d => d.IdPracownikNavigation).WithMany(p => p.WniosekUrlopowy)
                .HasForeignKey(d => d.IdPracownik)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Wniosek_u__ID_pr__534D60F1");

            entity.HasOne(d => d.IdUrlopuNavigation).WithMany(p => p.WniosekUrlopowy)
                .HasForeignKey(d => d.IdUrlopu)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Wniosek_u__ID_ur__5441852A");
        });

        modelBuilder.Entity<Wyposazenie>(entity =>
        {
            entity.HasKey(e => e.IdWyposazenie).HasName("PK__Wyposaze__39E58E718D3A752C");

            entity.Property(e => e.IdWyposazenie).HasColumnName("ID_wyposazenie");
            entity.Property(e => e.Nazwa)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Uwagi).HasMaxLength(250);
        });

        modelBuilder.Entity<WyposazenieWlasciwosci>(entity =>
        {
            entity.HasKey(e => e.IdWyposWlasc).HasName("PK__Wyposaze__9B2174247F5B5441");

            entity.ToTable("Wyposazenie_wlasciwosci");

            entity.Property(e => e.IdWyposWlasc).HasColumnName("ID_wypos_wlasc");
            entity.Property(e => e.IdWlasciwosci).HasColumnName("ID_wlasciwosci");
            entity.Property(e => e.IdWyposazenie).HasColumnName("ID_wyposazenie");
            entity.Property(e => e.Wartosc).HasColumnType("decimal(6, 2)");

            entity.HasOne(d => d.IdWlasciwosciNavigation).WithMany(p => p.WyposazenieWlasciwosci)
                .HasForeignKey(d => d.IdWlasciwosci)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Wyposazen__ID_wl__41EDCAC5");

            entity.HasOne(d => d.IdWyposazenieNavigation).WithMany(p => p.WyposazenieWlasciwosci)
                .HasForeignKey(d => d.IdWyposazenie)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Wyposazen__ID_wy__42E1EEFE");
        });

        modelBuilder.Entity<Wysylka>(entity =>
        {
            entity.HasKey(e => e.IdWysylka).HasName("PK__Wysylka__ED56F2DA9A425200");

            entity.Property(e => e.IdWysylka).HasColumnName("ID_wysylka");
            entity.Property(e => e.Cena).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.DataNadania).HasColumnName("Data_nadania");
        });

        modelBuilder.Entity<WysylkaZamowienie>(entity =>
        {
            entity.HasKey(e => e.IdWysylkaZamowienie).HasName("PK__Wysylka___0DE61031873891DB");

            entity.ToTable("Wysylka_zamowienie");

            entity.Property(e => e.IdWysylkaZamowienie).HasColumnName("ID_wysylka_zamowienie");
            entity.Property(e => e.IdWysylka).HasColumnName("ID_wysylka");
            entity.Property(e => e.IdZamowienie).HasColumnName("ID_zamowienie");

            entity.HasOne(d => d.IdWysylkaNavigation).WithMany(p => p.WysylkaZamowienie)
                .HasForeignKey(d => d.IdWysylka)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Wysylka_z__ID_wy__6FE99F9F");

            entity.HasOne(d => d.IdZamowienieNavigation).WithMany(p => p.WysylkaZamowienie)
                .HasForeignKey(d => d.IdZamowienie)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Wysylka_z__ID_za__6EF57B66");
        });

        modelBuilder.Entity<ZadanieProdukcyjne>(entity =>
        {
            entity.HasKey(e => e.IdZadanieP).HasName("PK__Zadanie___40247834A15C4A57");

            entity.ToTable("Zadanie_produkcyjne");

            entity.Property(e => e.IdZadanieP).HasColumnName("ID_zadanieP");
            entity.Property(e => e.DataZadania).HasColumnName("Data_zadania");
            entity.Property(e => e.IdMaszyna).HasColumnName("ID_maszyna");
            entity.Property(e => e.IdZamowienie).HasColumnName("ID_zamowienie");

            entity.HasOne(d => d.IdMaszynaNavigation).WithMany(p => p.ZadanieProdukcyjne)
                .HasForeignKey(d => d.IdMaszyna)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Zadanie_p__ID_ma__160F4887");

            entity.HasOne(d => d.IdZamowienieNavigation).WithMany(p => p.ZadanieProdukcyjne)
                .HasForeignKey(d => d.IdZamowienie)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Zadanie_p__ID_za__17036CC0");
        });

        modelBuilder.Entity<Zamowienie>(entity =>
        {
            entity.HasKey(e => e.IdZamowienie).HasName("PK__Zamowien__7BF8C9EF2FE56F60");

            entity.Property(e => e.IdZamowienie).HasColumnName("ID_zamowienie");
            entity.Property(e => e.DataPrzyjeciaZ).HasColumnName("Data_przyjecia_z");
            entity.Property(e => e.DataZrealizowaniaZ).HasColumnName("Data_zrealizowania_z");
            entity.Property(e => e.IdKlient).HasColumnName("ID_klient");

            entity.HasOne(d => d.IdKlientNavigation).WithMany(p => p.Zamowienie)
                .HasForeignKey(d => d.IdKlient)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Zamowieni__ID_kl__6C190EBB");
        });

        modelBuilder.Entity<ZwolnienieLekarskie>(entity =>
        {
            entity.HasKey(e => e.IdZwolnienie).HasName("PK__Zwolnien__3A67E027EB17144D");

            entity.ToTable("Zwolnienie_lekarskie");

            entity.Property(e => e.IdZwolnienie).HasColumnName("ID_zwolnienie");
            entity.Property(e => e.DataKoniec).HasColumnName("Data_koniec");
            entity.Property(e => e.DataPoczatek).HasColumnName("Data_poczatek");
            entity.Property(e => e.IdPracownik).HasColumnName("ID_pracownik");
            entity.Property(e => e.IdTypZwolnienia).HasColumnName("ID_typ_zwolnienia");
            entity.Property(e => e.Uwagi).HasMaxLength(255);

            entity.HasOne(d => d.IdPracownikNavigation).WithMany(p => p.ZwolnienieLekarskie)
                .HasForeignKey(d => d.IdPracownik)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Zwolnieni__ID_pr__4316F928");

            entity.HasOne(d => d.IdTypZwolnieniaNavigation).WithMany(p => p.ZwolnienieLekarskie)
                .HasForeignKey(d => d.IdTypZwolnienia)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Zwolnieni__ID_ty__440B1D61");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}