// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace PodkladexApp.Models;

public partial class PodkladexContext : DbContext
{
    public PodkladexContext()
    {
    }

    public PodkladexContext(DbContextOptions<PodkladexContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Awaria> Awaria { get; set; }

    public virtual DbSet<BadanieMedyczne> BadanieMedyczne { get; set; }

    public virtual DbSet<CzesciAwaria> CzesciAwaria { get; set; }

    public virtual DbSet<CzesciPrzeglady> CzesciPrzeglady { get; set; }

    public virtual DbSet<CzesciZamienne> CzesciZamienne { get; set; }

    public virtual DbSet<Dostawa> Dostawa { get; set; }

    public virtual DbSet<Firma> Firma { get; set; }

    public virtual DbSet<Gwarancja> Gwarancja { get; set; }

    public virtual DbSet<Jednostki> Jednostki { get; set; }

    public virtual DbSet<Klient> Klient { get; set; }

    public virtual DbSet<KlientFirma> KlientFirma { get; set; }

    public virtual DbSet<KontrolaMat> KontrolaMat { get; set; }

    public virtual DbSet<KontrolaProd> KontrolaProd { get; set; }

    public virtual DbSet<Maszyna> Maszyna { get; set; }

    public virtual DbSet<MaszynaTyp> MaszynaTyp { get; set; }

    public virtual DbSet<MaszynaWyp> MaszynaWyp { get; set; }

    public virtual DbSet<Material> Material { get; set; }

    public virtual DbSet<MaterialWlasciwosci> MaterialWlasciwosci { get; set; }

    public virtual DbSet<NormaProd> NormaProd { get; set; }

    public virtual DbSet<Normy> Normy { get; set; }

    public virtual DbSet<NormyEksploatacyjne> NormyEksploatacyjne { get; set; }

    public virtual DbSet<NormyMaszyna> NormyMaszyna { get; set; }

    public virtual DbSet<Obsluga> Obsluga { get; set; }

    public virtual DbSet<Osoba> Osoba { get; set; }

    public virtual DbSet<Pomiar> Pomiar { get; set; }

    public virtual DbSet<PomiarMat> PomiarMat { get; set; }

    public virtual DbSet<Pracownik> Pracownik { get; set; }

    public virtual DbSet<PracownikSzkolenia> PracownikSzkolenia { get; set; }

    public virtual DbSet<Produkcja> Produkcja { get; set; }

    public virtual DbSet<Produkty> Produkty { get; set; }

    public virtual DbSet<ProduktyNormy> ProduktyNormy { get; set; }

    public virtual DbSet<ProduktyWlasciwosci> ProduktyWlasciwosci { get; set; }

    public virtual DbSet<RodzajMaterialu> RodzajMaterialu { get; set; }

    public virtual DbSet<RodzajObslugi> RodzajObslugi { get; set; }

    public virtual DbSet<RodzajUmowy> RodzajUmowy { get; set; }

    public virtual DbSet<SiatkaPlac> SiatkaPlac { get; set; }

    public virtual DbSet<SzczegolyDostawy> SzczegolyDostawy { get; set; }

    public virtual DbSet<SzczegolyZamowienia> SzczegolyZamowienia { get; set; }

    public virtual DbSet<Szkolenia> Szkolenia { get; set; }

    public virtual DbSet<Typ> Typ { get; set; }

    public virtual DbSet<TypBadaniaMed> TypBadaniaMed { get; set; }

    public virtual DbSet<TypWlasciwosci> TypWlasciwosci { get; set; }

    public virtual DbSet<TypZwolnienie> TypZwolnienie { get; set; }

    public virtual DbSet<Umowa> Umowa { get; set; }

    public virtual DbSet<Urlop> Urlop { get; set; }

    public virtual DbSet<UrlopUmowa> UrlopUmowa { get; set; }

    public virtual DbSet<Wlasciwosci> Wlasciwosci { get; set; }

    public virtual DbSet<WniosekUrlopowy> WniosekUrlopowy { get; set; }

    public virtual DbSet<Wyposazenie> Wyposazenie { get; set; }

    public virtual DbSet<WyposazenieWlasciwosci> WyposazenieWlasciwosci { get; set; }

    public virtual DbSet<Wysylka> Wysylka { get; set; }

    public virtual DbSet<WysylkaZamowienie> WysylkaZamowienie { get; set; }

    public virtual DbSet<ZadanieProdukcyjne> ZadanieProdukcyjne { get; set; }

    public virtual DbSet<Zamowienie> Zamowienie { get; set; }

    public virtual DbSet<ZwolnienieLekarskie> ZwolnienieLekarskie { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=.\\MSSQLSERVER_KWZP;Initial Catalog=Podkladex;Persist Security Info=True;TrustServerCertificate=True; User ID=sa;Password=1qazXSW@");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Awaria>(entity =>
        {
            entity.HasKey(e => e.IdAwaria).HasName("PK__Awaria__8D4FCB836631D83D");

            entity.Property(e => e.IdAwaria).HasColumnName("ID_awaria");
            entity.Property(e => e.DataUsuniecia).HasColumnName("Data_usuniecia");
            entity.Property(e => e.DataZgloszenia).HasColumnName("Data_zgloszenia");
            entity.Property(e => e.IdMaszyna).HasColumnName("ID_maszyna");
            entity.Property(e => e.IdPracownik).HasColumnName("ID_pracownik");
            entity.Property(e => e.Opis)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.IdMaszynaNavigation).WithMany(p => p.Awaria)
                .HasForeignKey(d => d.IdMaszyna)
                .HasConstraintName("FK__Awaria__ID_maszy__4E53A1AA");

            entity.HasOne(d => d.IdPracownikNavigation).WithMany(p => p.Awaria)
                .HasForeignKey(d => d.IdPracownik)
                .HasConstraintName("FK__Awaria__ID_praco__4F47C5E3");
        });

        modelBuilder.Entity<BadanieMedyczne>(entity =>
        {
            entity.HasKey(e => e.IdBadanieMedyczne).HasName("PK__Badanie___D27847BAE7ED9E40");

            entity.ToTable("Badanie_medyczne");

            entity.Property(e => e.IdBadanieMedyczne).HasColumnName("ID_badanie_medyczne");
            entity.Property(e => e.DataBadania).HasColumnName("Data_badania");
            entity.Property(e => e.DataWaznosci).HasColumnName("Data_waznosci");
            entity.Property(e => e.IdPracownik).HasColumnName("ID_pracownik");
            entity.Property(e => e.IdTypBadaniaMed).HasColumnName("ID_typ_badania_med");
            entity.Property(e => e.Koszt).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Uwagi).HasMaxLength(255);

            entity.HasOne(d => d.IdPracownikNavigation).WithMany(p => p.BadanieMedyczne)
                .HasForeignKey(d => d.IdPracownik)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Badanie_m__ID_pr__47DBAE45");

            entity.HasOne(d => d.IdTypBadaniaMedNavigation).WithMany(p => p.BadanieMedyczne)
                .HasForeignKey(d => d.IdTypBadaniaMed)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Badanie_m__ID_ty__48CFD27E");
        });

        modelBuilder.Entity<CzesciAwaria>(entity =>
        {
            entity.HasKey(e => e.IdCzesciAwaria).HasName("PK__Czesci_a__2A11CA5C1769BFB9");

            entity.ToTable("Czesci_awaria");

            entity.Property(e => e.IdCzesciAwaria).HasColumnName("ID_Czesci_awaria");
            entity.Property(e => e.IdAwaria).HasColumnName("ID_awaria");
            entity.Property(e => e.IdCzesci).HasColumnName("ID_czesci");

            entity.HasOne(d => d.IdAwariaNavigation).WithMany(p => p.CzesciAwaria)
                .HasForeignKey(d => d.IdAwaria)
                .HasConstraintName("FK__Czesci_aw__ID_aw__531856C7");

            entity.HasOne(d => d.IdCzesciNavigation).WithMany(p => p.CzesciAwaria)
                .HasForeignKey(d => d.IdCzesci)
                .HasConstraintName("FK__Czesci_aw__ID_cz__5224328E");
        });

        modelBuilder.Entity<CzesciPrzeglady>(entity =>
        {
            entity.HasKey(e => e.IdCzesciPrzeglady).HasName("PK__Czesci_p__025E78FC0D2F2E34");

            entity.ToTable("Czesci_przeglady");

            entity.Property(e => e.IdCzesciPrzeglady).HasColumnName("ID_Czesci_przeglady");
            entity.Property(e => e.IdCzesci).HasColumnName("ID_czesci");
            entity.Property(e => e.IdObsluga).HasColumnName("ID_obsluga");
            entity.Property(e => e.Opis)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.IdCzesciNavigation).WithMany(p => p.CzesciPrzeglady)
                .HasForeignKey(d => d.IdCzesci)
                .HasConstraintName("FK__Czesci_pr__ID_cz__625A9A57");

            entity.HasOne(d => d.IdObslugaNavigation).WithMany(p => p.CzesciPrzeglady)
                .HasForeignKey(d => d.IdObsluga)
                .HasConstraintName("FK__Czesci_pr__ID_ob__634EBE90");
        });

        modelBuilder.Entity<CzesciZamienne>(entity =>
        {
            entity.HasKey(e => e.IdCzesci).HasName("PK__Czesci_z__3566F7994C9CFAA1");

            entity.ToTable("Czesci_zamienne");

            entity.Property(e => e.IdCzesci).HasColumnName("ID_czesci");
            entity.Property(e => e.Nazwa)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Dostawa>(entity =>
        {
            entity.HasKey(e => e.IdDostawa).HasName("PK__Dostawa__6D6331123B3357D7");

            entity.Property(e => e.IdDostawa).HasColumnName("ID_dostawa");
            entity.Property(e => e.DataDostawy).HasColumnName("Data_dostawy");
            entity.Property(e => e.IdFirma).HasColumnName("ID_firma");
            entity.Property(e => e.IdMaterial).HasColumnName("ID_material");
            entity.Property(e => e.IdPracownik).HasColumnName("ID_pracownik");

            entity.HasOne(d => d.IdFirmaNavigation).WithMany(p => p.Dostawa)
                .HasForeignKey(d => d.IdFirma)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Dostawa__ID_firm__18EBB532");

            entity.HasOne(d => d.IdMaterialNavigation).WithMany(p => p.Dostawa)
                .HasForeignKey(d => d.IdMaterial)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Dostawa__ID_mate__17F790F9");

            entity.HasOne(d => d.IdPracownikNavigation).WithMany(p => p.Dostawa)
                .HasForeignKey(d => d.IdPracownik)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Dostawa__ID_prac__19DFD96B");
        });

        modelBuilder.Entity<Firma>(entity =>
        {
            entity.HasKey(e => e.IdFirma).HasName("PK__Firma__30DD244AA160F354");

            entity.Property(e => e.IdFirma).HasColumnName("ID_firma");
            entity.Property(e => e.KodPocztowy)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Kod_pocztowy");
            entity.Property(e => e.Miejscowosc)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Nazwa)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Nip)
                .IsRequired()
                .HasMaxLength(13)
                .IsUnicode(false)
                .HasColumnName("NIP");
            entity.Property(e => e.Numer)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.Ulica)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Gwarancja>(entity =>
        {
            entity.HasKey(e => e.IdGwarancja).HasName("PK__Gwarancj__06520D255BA47B6A");

            entity.Property(e => e.IdGwarancja).HasColumnName("ID_gwarancja");
            entity.Property(e => e.CzasGwarancji)
                .HasColumnType("decimal(6, 2)")
                .HasColumnName("Czas_gwarancji");
            entity.Property(e => e.IdFirma).HasColumnName("ID_firma");
            entity.Property(e => e.IdMaszyna).HasColumnName("ID_maszyna");
            entity.Property(e => e.Warunki).HasMaxLength(250);

            entity.HasOne(d => d.IdFirmaNavigation).WithMany(p => p.Gwarancja)
                .HasForeignKey(d => d.IdFirma)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Gwarancja__ID_fi__40058253");

            entity.HasOne(d => d.IdMaszynaNavigation).WithMany(p => p.Gwarancja)
                .HasForeignKey(d => d.IdMaszyna)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Gwarancja__ID_ma__3F115E1A");
        });

        modelBuilder.Entity<Jednostki>(entity =>
        {
            entity.HasKey(e => e.IdJednostki).HasName("PK__Jednostk__B50E042FC0A649C2");

            entity.Property(e => e.IdJednostki).HasColumnName("ID_jednostki");
            entity.Property(e => e.NazwaJednostki)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("Nazwa_jednostki");
        });

        modelBuilder.Entity<Klient>(entity =>
        {
            entity.HasKey(e => e.IdKlient).HasName("PK__Klient__7382667EE0D97AFE");

            entity.Property(e => e.IdKlient).HasColumnName("ID_klient");
            entity.Property(e => e.IdOsoba).HasColumnName("ID_osoba");

            entity.HasOne(d => d.IdOsobaNavigation).WithMany(p => p.Klient)
                .HasForeignKey(d => d.IdOsoba)
                .HasConstraintName("FK__Klient__ID_osoba__59FA5E80");
        });

        modelBuilder.Entity<KlientFirma>(entity =>
        {
            entity.HasKey(e => e.IdKlientFirma).HasName("PK__Klient_f__2AAE6DA7A9885AF2");

            entity.ToTable("Klient_firma");

            entity.Property(e => e.IdKlientFirma).HasColumnName("ID_klient_firma");
            entity.Property(e => e.DataKoniec).HasColumnName("Data_koniec");
            entity.Property(e => e.DataPocz).HasColumnName("Data_pocz");
            entity.Property(e => e.IdFirma).HasColumnName("ID_firma");
            entity.Property(e => e.IdKlient).HasColumnName("ID_klient");

            entity.HasOne(d => d.IdFirmaNavigation).WithMany(p => p.KlientFirma)
                .HasForeignKey(d => d.IdFirma)
                .HasConstraintName("FK__Klient_fi__ID_fi__5FB337D6");

            entity.HasOne(d => d.IdKlientNavigation).WithMany(p => p.KlientFirma)
                .HasForeignKey(d => d.IdKlient)
                .HasConstraintName("FK__Klient_fi__ID_kl__5EBF139D");
        });

        modelBuilder.Entity<KontrolaMat>(entity =>
        {
            entity.HasKey(e => e.IdKontrolaMat).HasName("PK__Kontrola__5856399FA11CC992");

            entity.ToTable("Kontrola_mat");

            entity.Property(e => e.IdKontrolaMat).HasColumnName("ID_Kontrola_mat");
            entity.Property(e => e.IdMaterial).HasColumnName("ID_material");
            entity.Property(e => e.IdPracownik).HasColumnName("ID_pracownik");
            entity.Property(e => e.IdZadanieP).HasColumnName("ID_zadanieP");
            entity.Property(e => e.Odpady).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Rbh)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("RBH");

            entity.HasOne(d => d.IdMaterialNavigation).WithMany(p => p.KontrolaMat)
                .HasForeignKey(d => d.IdMaterial)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Kontrola___ID_ma__6FE99F9F");

            entity.HasOne(d => d.IdPracownikNavigation).WithMany(p => p.KontrolaMat)
                .HasForeignKey(d => d.IdPracownik)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Kontrola___ID_pr__70DDC3D8");

            entity.HasOne(d => d.IdZadaniePNavigation).WithMany(p => p.KontrolaMat)
                .HasForeignKey(d => d.IdZadanieP)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Kontrola___ID_za__6EF57B66");
        });

        modelBuilder.Entity<KontrolaProd>(entity =>
        {
            entity.HasKey(e => e.IdKontrolaProd).HasName("PK__Kontrola__3831EE890361B098");

            entity.ToTable("Kontrola_prod");

            entity.Property(e => e.IdKontrolaProd).HasColumnName("ID_Kontrola_prod");
            entity.Property(e => e.IdPracownik).HasColumnName("ID_pracownik");
            entity.Property(e => e.IdZadanieP).HasColumnName("ID_zadanieP");
            entity.Property(e => e.Odpady).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Rbh)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("RBH");

            entity.HasOne(d => d.IdPracownikNavigation).WithMany(p => p.KontrolaProd)
                .HasForeignKey(d => d.IdPracownik)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Kontrola___ID_pr__74AE54BC");

            entity.HasOne(d => d.IdZadaniePNavigation).WithMany(p => p.KontrolaProd)
                .HasForeignKey(d => d.IdZadanieP)
                .HasConstraintName("FK__Kontrola___ID_za__73BA3083");
        });

        modelBuilder.Entity<Maszyna>(entity =>
        {
            entity.HasKey(e => e.IdMaszyna).HasName("PK__Maszyna__38E0F77ACD87C222");

            entity.Property(e => e.IdMaszyna).HasColumnName("ID_maszyna");
            entity.Property(e => e.DataUruchomienia).HasColumnName("Data_uruchomienia");
            entity.Property(e => e.DataWylaczenia).HasColumnName("Data_wylaczenia");
            entity.Property(e => e.DataZakupu).HasColumnName("Data_zakupu");
            entity.Property(e => e.Nazwa)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Uwagi).HasMaxLength(250);
        });

        modelBuilder.Entity<MaszynaTyp>(entity =>
        {
            entity.HasKey(e => e.IdMaszynaTyp).HasName("PK__Maszyna___EFC428C51777633C");

            entity.ToTable("Maszyna_typ");

            entity.Property(e => e.IdMaszynaTyp).HasColumnName("ID_maszyna_typ");
            entity.Property(e => e.IdMaszyna).HasColumnName("ID_maszyna");
            entity.Property(e => e.IdTyp).HasColumnName("ID_typ");

            entity.HasOne(d => d.IdMaszynaNavigation).WithMany(p => p.MaszynaTyp)
                .HasForeignKey(d => d.IdMaszyna)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Maszyna_t__ID_ma__29221CFB");

            entity.HasOne(d => d.IdTypNavigation).WithMany(p => p.MaszynaTyp)
                .HasForeignKey(d => d.IdTyp)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Maszyna_t__ID_ty__282DF8C2");
        });

        modelBuilder.Entity<MaszynaWyp>(entity =>
        {
            entity.HasKey(e => e.IdMaszynaWyp).HasName("PK__Maszyna___EC15EAC362C4E1D0");

            entity.ToTable("Maszyna_wyp");

            entity.Property(e => e.IdMaszynaWyp).HasColumnName("ID_maszyna_wyp");
            entity.Property(e => e.IdMaszyna).HasColumnName("ID_maszyna");
            entity.Property(e => e.IdNormaP).HasColumnName("ID_normaP");
            entity.Property(e => e.IdWyposazenie).HasColumnName("ID_wyposazenie");

            entity.HasOne(d => d.IdMaszynaNavigation).WithMany(p => p.MaszynaWyp)
                .HasForeignKey(d => d.IdMaszyna)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Maszyna_w__ID_ma__3B40CD36");

            entity.HasOne(d => d.IdNormaPNavigation).WithMany(p => p.MaszynaWyp)
                .HasForeignKey(d => d.IdNormaP)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Maszyna_w__ID_no__3A4CA8FD");

            entity.HasOne(d => d.IdWyposazenieNavigation).WithMany(p => p.MaszynaWyp)
                .HasForeignKey(d => d.IdWyposazenie)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Maszyna_w__ID_wy__3C34F16F");
        });

        modelBuilder.Entity<Material>(entity =>
        {
            entity.HasKey(e => e.IdMaterial).HasName("PK__Material__DF85261063895AD1");

            entity.Property(e => e.IdMaterial).HasColumnName("ID_material");
            entity.Property(e => e.Nazwa)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Opis)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<MaterialWlasciwosci>(entity =>
        {
            entity.HasKey(e => e.IdMaterialWlasciwosci).HasName("PK__Material__6D0188712D6E0A45");

            entity.ToTable("Material_wlasciwosci");

            entity.Property(e => e.IdMaterialWlasciwosci).HasColumnName("ID_material_wlasciwosci");
            entity.Property(e => e.IdMaterial).HasColumnName("ID_material");
            entity.Property(e => e.IdWlasciwosci).HasColumnName("ID_wlasciwosci");
            entity.Property(e => e.WartoscMaksymalna)
                .HasColumnType("decimal(6, 2)")
                .HasColumnName("Wartosc_maksymalna");
            entity.Property(e => e.WartoscMinimalna)
                .HasColumnType("decimal(6, 2)")
                .HasColumnName("Wartosc_minimalna");

            entity.HasOne(d => d.IdMaterialNavigation).WithMany(p => p.MaterialWlasciwosci)
                .HasForeignKey(d => d.IdMaterial)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Material___ID_ma__151B244E");

            entity.HasOne(d => d.IdWlasciwosciNavigation).WithMany(p => p.MaterialWlasciwosci)
                .HasForeignKey(d => d.IdWlasciwosci)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Material___ID_wl__14270015");
        });

        modelBuilder.Entity<NormaProd>(entity =>
        {
            entity.HasKey(e => e.IdNormaP).HasName("PK__Norma_pr__FD73E4886D280A39");

            entity.ToTable("Norma_prod");

            entity.Property(e => e.IdNormaP).HasColumnName("ID_normaP");
            entity.Property(e => e.Czas).HasColumnType("decimal(6, 2)");
            entity.Property(e => e.Data).HasColumnName("Data_");
            entity.Property(e => e.IdMaterial).HasColumnName("ID_material");
            entity.Property(e => e.IdProdukt).HasColumnName("ID_produkt");
            entity.Property(e => e.Ilosc).HasColumnType("decimal(6, 2)");
            entity.Property(e => e.IloscMat)
                .HasColumnType("decimal(6, 2)")
                .HasColumnName("Ilosc_mat");

            entity.HasOne(d => d.IdMaterialNavigation).WithMany(p => p.NormaProd)
                .HasForeignKey(d => d.IdMaterial)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Norma_pro__ID_ma__32AB8735");

            entity.HasOne(d => d.IdProduktNavigation).WithMany(p => p.NormaProd)
                .HasForeignKey(d => d.IdProdukt)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Norma_pro__ID_pr__31B762FC");
        });

        modelBuilder.Entity<Normy>(entity =>
        {
            entity.HasKey(e => e.IdNormy).HasName("PK__Normy__E42B5C524EA5CDF1");

            entity.Property(e => e.IdNormy).HasColumnName("ID_normy");
            entity.Property(e => e.Nazwa)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Opis)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<NormyEksploatacyjne>(entity =>
        {
            entity.HasKey(e => e.IdNormyEkspl).HasName("PK__Normy_ek__63D2F7FE286FB922");

            entity.ToTable("Normy_eksploatacyjne");

            entity.Property(e => e.IdNormyEkspl).HasColumnName("ID_normy_ekspl");
            entity.Property(e => e.NazwaNormy)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("Nazwa_normy");
            entity.Property(e => e.PrzebiegNorma)
                .HasColumnType("decimal(6, 2)")
                .HasColumnName("Przebieg_norma");
        });

        modelBuilder.Entity<NormyMaszyna>(entity =>
        {
            entity.HasKey(e => e.IdNormyMaszyna).HasName("PK__Normy_ma__F353B32B5ED302B9");

            entity.ToTable("Normy_maszyna");

            entity.Property(e => e.IdNormyMaszyna).HasColumnName("ID_Normy_maszyna");
            entity.Property(e => e.IdMaszyna).HasColumnName("ID_maszyna");
            entity.Property(e => e.IdNormyEkspl).HasColumnName("ID_normy_ekspl");
            entity.Property(e => e.Wartosc).HasColumnType("decimal(6, 2)");

            entity.HasOne(d => d.IdMaszynaNavigation).WithMany(p => p.NormyMaszyna)
                .HasForeignKey(d => d.IdMaszyna)
                .HasConstraintName("FK__Normy_mas__ID_ma__5F7E2DAC");

            entity.HasOne(d => d.IdNormyEksplNavigation).WithMany(p => p.NormyMaszyna)
                .HasForeignKey(d => d.IdNormyEkspl)
                .HasConstraintName("FK__Normy_mas__ID_no__5E8A0973");
        });

        modelBuilder.Entity<Obsluga>(entity =>
        {
            entity.HasKey(e => e.IdObsluga).HasName("PK__Obsluga__5F5AD476F2A3D35F");

            entity.Property(e => e.IdObsluga).HasColumnName("ID_obsluga");
            entity.Property(e => e.DataKoniec).HasColumnName("Data_koniec");
            entity.Property(e => e.DataPoczatek).HasColumnName("Data_poczatek");
            entity.Property(e => e.IdMaszyna).HasColumnName("ID_maszyna");
            entity.Property(e => e.IdPracownik).HasColumnName("ID_pracownik");
            entity.Property(e => e.IdRodzajObslugi).HasColumnName("ID_rodzaj_obslugi");
            entity.Property(e => e.Przebieg).HasColumnType("decimal(6, 2)");
            entity.Property(e => e.Uwagi)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.IdMaszynaNavigation).WithMany(p => p.Obsluga)
                .HasForeignKey(d => d.IdMaszyna)
                .HasConstraintName("FK__Obsluga__ID_masz__57DD0BE4");

            entity.HasOne(d => d.IdPracownikNavigation).WithMany(p => p.Obsluga)
                .HasForeignKey(d => d.IdPracownik)
                .HasConstraintName("FK__Obsluga__ID_prac__58D1301D");

            entity.HasOne(d => d.IdRodzajObslugiNavigation).WithMany(p => p.Obsluga)
                .HasForeignKey(d => d.IdRodzajObslugi)
                .HasConstraintName("FK__Obsluga__ID_rodz__59C55456");
        });

        modelBuilder.Entity<Osoba>(entity =>
        {
            entity.HasKey(e => e.IdOsoba).HasName("PK__Osoba__7573A6972F7B08F5");

            entity.Property(e => e.IdOsoba).HasColumnName("ID_osoba");
            entity.Property(e => e.AdresEMail)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("Adres_e_mail");
            entity.Property(e => e.Imie)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.KodPocztowy)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("Kod_pocztowy");
            entity.Property(e => e.Miejscowosc)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Nazwisko)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.NrTelefonu)
                .IsRequired()
                .HasMaxLength(12)
                .HasColumnName("Nr_telefonu");
            entity.Property(e => e.Numer)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.Pesel)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("PESEL");
            entity.Property(e => e.Ulica)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Pomiar>(entity =>
        {
            entity.HasKey(e => e.IdPomiar).HasName("PK__Pomiar__D471E709D67F0624");

            entity.Property(e => e.IdPomiar).HasColumnName("ID_Pomiar");
            entity.Property(e => e.IdKontrolaProd).HasColumnName("ID_Kontrola_prod");
            entity.Property(e => e.IdWlasciwosci).HasColumnName("ID_wlasciwosci");
            entity.Property(e => e.WartoscZmierzona)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("Wartosc_zmierzona");

            entity.HasOne(d => d.IdKontrolaProdNavigation).WithMany(p => p.Pomiar)
                .HasForeignKey(d => d.IdKontrolaProd)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Pomiar__ID_Kontr__05D8E0BE");

            entity.HasOne(d => d.IdWlasciwosciNavigation).WithMany(p => p.Pomiar)
                .HasForeignKey(d => d.IdWlasciwosci)
                .HasConstraintName("FK__Pomiar__ID_wlasc__04E4BC85");
        });

        modelBuilder.Entity<PomiarMat>(entity =>
        {
            entity.HasKey(e => e.IdPomiarMat).HasName("PK__Pomiar_m__846501809A01B759");

            entity.ToTable("Pomiar_mat");

            entity.Property(e => e.IdPomiarMat).HasColumnName("ID_Pomiar_mat");
            entity.Property(e => e.IdKontrolaMat).HasColumnName("ID_Kontrola_mat");
            entity.Property(e => e.IdWlasciwosci).HasColumnName("ID_wlasciwosci");
            entity.Property(e => e.WartoscZmierzona)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("Wartosc_zmierzona");

            entity.HasOne(d => d.IdKontrolaMatNavigation).WithMany(p => p.PomiarMat)
                .HasForeignKey(d => d.IdKontrolaMat)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Pomiar_ma__ID_Ko__08B54D69");

            entity.HasOne(d => d.IdWlasciwosciNavigation).WithMany(p => p.PomiarMat)
                .HasForeignKey(d => d.IdWlasciwosci)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Pomiar_ma__ID_wl__09A971A2");
        });

        modelBuilder.Entity<Pracownik>(entity =>
        {
            entity.HasKey(e => e.IdPracownik).HasName("PK__Pracowni__4AE49B6E3597EF8F");

            entity.Property(e => e.IdPracownik).HasColumnName("ID_pracownik");
            entity.Property(e => e.IdOsoba).HasColumnName("ID_osoba");

            entity.HasOne(d => d.IdOsobaNavigation).WithMany(p => p.Pracownik)
                .HasForeignKey(d => d.IdOsoba)
                .HasConstraintName("FK__Pracownik__ID_os__398D8EEE");
        });

        modelBuilder.Entity<PracownikSzkolenia>(entity =>
        {
            entity.HasKey(e => new { e.IdPracownik, e.IdSzkolenia, e.DataSzkolenia }).HasName("PK__Pracowni__B6A6B4AD40B89BA6");

            entity.ToTable("Pracownik_szkolenia");

            entity.Property(e => e.IdPracownik).HasColumnName("ID_pracownik");
            entity.Property(e => e.IdSzkolenia).HasColumnName("ID_szkolenia");
            entity.Property(e => e.DataSzkolenia).HasColumnName("Data_szkolenia");
            entity.Property(e => e.CenaSzkolenia)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("Cena_szkolenia");
            entity.Property(e => e.DataWaznosci).HasColumnName("Data_waznosci");

            entity.HasOne(d => d.IdPracownikNavigation).WithMany(p => p.PracownikSzkolenia)
                .HasForeignKey(d => d.IdPracownik)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Pracownik__ID_pr__4E88ABD4");

            entity.HasOne(d => d.IdSzkoleniaNavigation).WithMany(p => p.PracownikSzkolenia)
                .HasForeignKey(d => d.IdSzkolenia)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Pracownik__ID_sz__4F7CD00D");
        });

        modelBuilder.Entity<Produkcja>(entity =>
        {
            entity.HasKey(e => e.IdProdukcja).HasName("PK__Produkcj__69A3FC990A60BC3C");

            entity.Property(e => e.IdProdukcja).HasColumnName("ID_produkcja");
            entity.Property(e => e.IdNormyP).HasColumnName("ID_normyP");
            entity.Property(e => e.IdPracownik).HasColumnName("ID_pracownik");
            entity.Property(e => e.IdZadanieP).HasColumnName("ID_zadanieP");
            entity.Property(e => e.Odpady).HasColumnType("decimal(6, 2)");
            entity.Property(e => e.Rbh)
                .HasColumnType("decimal(4, 2)")
                .HasColumnName("RBH");
            entity.Property(e => e.Wyprodukowano).HasColumnType("decimal(6, 2)");

            entity.HasOne(d => d.IdNormyPNavigation).WithMany(p => p.Produkcja)
                .HasForeignKey(d => d.IdNormyP)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Produkcja__ID_no__37703C52");

            entity.HasOne(d => d.IdPracownikNavigation).WithMany(p => p.Produkcja)
                .HasForeignKey(d => d.IdPracownik)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Produkcja__ID_pr__3587F3E0");

            entity.HasOne(d => d.IdZadaniePNavigation).WithMany(p => p.Produkcja)
                .HasForeignKey(d => d.IdZadanieP)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Produkcja__ID_za__367C1819");
        });

        modelBuilder.Entity<Produkty>(entity =>
        {
            entity.HasKey(e => e.IdProdukt).HasName("PK__Produkty__FD71AB0DF007FFA8");

            entity.Property(e => e.IdProdukt).HasColumnName("ID_produkt");
            entity.Property(e => e.Nazwa)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<ProduktyNormy>(entity =>
        {
            entity.HasKey(e => e.IdProduktyNormy).HasName("PK__Produkty__4247AF0F2D231166");

            entity.ToTable("Produkty_Normy");

            entity.Property(e => e.IdProduktyNormy).HasColumnName("ID_produkty_normy");
            entity.Property(e => e.IdNormy).HasColumnName("ID_normy");
            entity.Property(e => e.IdProdukt).HasColumnName("ID_produkt");

            entity.HasOne(d => d.IdNormyNavigation).WithMany(p => p.ProduktyNormy)
                .HasForeignKey(d => d.IdNormy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Produkty___ID_no__0C85DE4D");

            entity.HasOne(d => d.IdProduktNavigation).WithMany(p => p.ProduktyNormy)
                .HasForeignKey(d => d.IdProdukt)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Produkty___ID_pr__0D7A0286");
        });

        modelBuilder.Entity<ProduktyWlasciwosci>(entity =>
        {
            entity.HasKey(e => e.IdProduktyWlasciwosci).HasName("PK__Produkty__AA8BF23404C18BEB");

            entity.ToTable("Produkty_wlasciwosci");

            entity.Property(e => e.IdProduktyWlasciwosci).HasColumnName("ID_produkty_wlasciwosci");
            entity.Property(e => e.IdProdukt).HasColumnName("ID_produkt");
            entity.Property(e => e.IdWlasciwosci).HasColumnName("ID_wlasciwosci");
            entity.Property(e => e.WartoscMaksymalna)
                .HasColumnType("decimal(6, 2)")
                .HasColumnName("Wartosc_maksymalna");
            entity.Property(e => e.WartoscMinimalna)
                .HasColumnType("decimal(6, 2)")
                .HasColumnName("Wartosc_minimalna");

            entity.HasOne(d => d.IdProduktNavigation).WithMany(p => p.ProduktyWlasciwosci)
                .HasForeignKey(d => d.IdProdukt)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Produkty___ID_pr__114A936A");

            entity.HasOne(d => d.IdWlasciwosciNavigation).WithMany(p => p.ProduktyWlasciwosci)
                .HasForeignKey(d => d.IdWlasciwosci)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Produkty___ID_wl__10566F31");
        });

        modelBuilder.Entity<RodzajMaterialu>(entity =>
        {
            entity.HasKey(e => e.IdRodzaj).HasName("PK__Rodzaj_m__5605F872B17CF6A5");

            entity.ToTable("Rodzaj_materialu");

            entity.Property(e => e.IdRodzaj).HasColumnName("ID_rodzaj");
            entity.Property(e => e.Nazwa)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<RodzajObslugi>(entity =>
        {
            entity.HasKey(e => e.IdRodzajObslugi).HasName("PK__Rodzaj_o__CCBEB0F8D1D51775");

            entity.ToTable("Rodzaj_obslugi");

            entity.Property(e => e.IdRodzajObslugi).HasColumnName("ID_rodzaj_obslugi");
            entity.Property(e => e.Nazwa)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Opis)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<RodzajUmowy>(entity =>
        {
            entity.HasKey(e => e.IdRodzaju).HasName("PK__Rodzaj_u__5001DC833DBB20F4");

            entity.ToTable("Rodzaj_umowy");

            entity.Property(e => e.IdRodzaju).HasColumnName("ID_rodzaju");
            entity.Property(e => e.Nazwa)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Opis)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<SiatkaPlac>(entity =>
        {
            entity.HasKey(e => e.IdSiatkaPlac).HasName("PK__Siatka_p__487C8DBECEB22C2F");

            entity.ToTable("Siatka_plac");

            entity.Property(e => e.IdSiatkaPlac).HasColumnName("ID_siatka_plac");
            entity.Property(e => e.DataKoniec).HasColumnName("Data_koniec");
            entity.Property(e => e.DataPocz).HasColumnName("Data_pocz");
            entity.Property(e => e.IdPracownik).HasColumnName("ID_pracownik");
            entity.Property(e => e.Wynagrodzenie).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.IdPracownikNavigation).WithMany(p => p.SiatkaPlac)
                .HasForeignKey(d => d.IdPracownik)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Siatka_pl__ID_pr__4BAC3F29");
        });

        modelBuilder.Entity<SzczegolyDostawy>(entity =>
        {
            entity.HasKey(e => e.IdSzczegolyDostawy).HasName("PK__Szczegol__C5FC719BBA1BEFFB");

            entity.ToTable("Szczegoly_dostawy");

            entity.Property(e => e.IdSzczegolyDostawy).HasColumnName("ID_szczegoly_dostawy");
            entity.Property(e => e.Cena).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.IdDostawa).HasColumnName("ID_dostawa");
            entity.Property(e => e.IdRodzaj).HasColumnName("ID_rodzaj");
            entity.Property(e => e.Liczba).HasColumnType("decimal(6, 2)");

            entity.HasOne(d => d.IdDostawaNavigation).WithMany(p => p.SzczegolyDostawy)
                .HasForeignKey(d => d.IdDostawa)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Szczegoly__ID_do__1EA48E88");

            entity.HasOne(d => d.IdRodzajNavigation).WithMany(p => p.SzczegolyDostawy)
                .HasForeignKey(d => d.IdRodzaj)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Szczegoly__ID_ro__1F98B2C1");
        });

        modelBuilder.Entity<SzczegolyZamowienia>(entity =>
        {
            entity.HasKey(e => e.IdSzczegolyZamowienia).HasName("PK__Szczegol__2D26C348B0BF7080");

            entity.ToTable("Szczegoly_zamowienia");

            entity.Property(e => e.IdSzczegolyZamowienia).HasColumnName("ID_szczegoly_zamowienia");
            entity.Property(e => e.Cena).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.IdMaterial).HasColumnName("ID_material");
            entity.Property(e => e.IdProdukt).HasColumnName("ID_produkt");
            entity.Property(e => e.IdZamowienie).HasColumnName("ID_zamowienie");
            entity.Property(e => e.Ilosc).HasColumnType("decimal(6, 2)");
            entity.Property(e => e.Uwagi).HasMaxLength(255);

            entity.HasOne(d => d.IdMaterialNavigation).WithMany(p => p.SzczegolyZamowienia)
                .HasForeignKey(d => d.IdMaterial)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Szczegoly__ID_ma__7B5B524B");

            entity.HasOne(d => d.IdProduktNavigation).WithMany(p => p.SzczegolyZamowienia)
                .HasForeignKey(d => d.IdProdukt)
                .HasConstraintName("FK__Szczegoly__ID_pr__7A672E12");

            entity.HasOne(d => d.IdZamowienieNavigation).WithMany(p => p.SzczegolyZamowienia)
                .HasForeignKey(d => d.IdZamowienie)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Szczegoly__ID_za__797309D9");
        });

        modelBuilder.Entity<Szkolenia>(entity =>
        {
            entity.HasKey(e => e.IdSzkolenia).HasName("PK__Szkoleni__8655159D6D419B56");

            entity.Property(e => e.IdSzkolenia).HasColumnName("ID_szkolenia");
            entity.Property(e => e.CzyObowiazkowe).HasColumnName("Czy_obowiazkowe");
            entity.Property(e => e.Nazwa)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Opis).HasMaxLength(255);
            entity.Property(e => e.WaznoscObowiazkowe).HasColumnName("Waznosc_obowiazkowe");
        });

        modelBuilder.Entity<Typ>(entity =>
        {
            entity.HasKey(e => e.IdTyp).HasName("PK__Typ__1FBE6678477AECFE");

            entity.Property(e => e.IdTyp).HasColumnName("ID_typ");
            entity.Property(e => e.Nazwa)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<TypBadaniaMed>(entity =>
        {
            entity.HasKey(e => e.IdTypBadaniaMed).HasName("PK__Typ_bada__E8E973F31D0579A8");

            entity.ToTable("Typ_badania_med");

            entity.Property(e => e.IdTypBadaniaMed).HasColumnName("ID_typ_badania_med");
            entity.Property(e => e.Nazwa)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Opis).HasMaxLength(255);
        });

        modelBuilder.Entity<TypWlasciwosci>(entity =>
        {
            entity.HasKey(e => e.IdTypWlasciwosci).HasName("PK__Typ_wlas__637DFEB78C47AC50");

            entity.ToTable("Typ_wlasciwosci");

            entity.Property(e => e.IdTypWlasciwosci).HasColumnName("ID_typ_wlasciwosci");
            entity.Property(e => e.IdTyp).HasColumnName("ID_typ");
            entity.Property(e => e.IdWlasciwosci).HasColumnName("ID_wlasciwosci");
            entity.Property(e => e.Wartosc).HasColumnType("decimal(6, 2)");

            entity.HasOne(d => d.IdTypNavigation).WithMany(p => p.TypWlasciwosci)
                .HasForeignKey(d => d.IdTyp)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Typ_wlasc__ID_ty__25518C17");

            entity.HasOne(d => d.IdWlasciwosciNavigation).WithMany(p => p.TypWlasciwosci)
                .HasForeignKey(d => d.IdWlasciwosci)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Typ_wlasc__ID_wl__245D67DE");
        });

        modelBuilder.Entity<TypZwolnienie>(entity =>
        {
            entity.HasKey(e => e.IdTypZwolnienia).HasName("PK__Typ_zwol__3E15685940B07D0C");

            entity.ToTable("Typ_zwolnienie");

            entity.Property(e => e.IdTypZwolnienia).HasColumnName("ID_typ_zwolnienia");
            entity.Property(e => e.Nazwa)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Opis).HasMaxLength(255);
        });

        modelBuilder.Entity<Umowa>(entity =>
        {
            entity.HasKey(e => e.IdUmowa).HasName("PK__Umowa__D2EDF6FB9C5E312B");

            entity.Property(e => e.IdUmowa).HasColumnName("ID_umowa");
            entity.Property(e => e.DataRoz).HasColumnName("Data_roz");
            entity.Property(e => e.DataZak).HasColumnName("Data_zak");
            entity.Property(e => e.IdPracownik).HasColumnName("ID_pracownik");
            entity.Property(e => e.IdRodzaju).HasColumnName("ID_rodzaju");

            entity.HasOne(d => d.IdPracownikNavigation).WithMany(p => p.Umowa)
                .HasForeignKey(d => d.IdPracownik)
                .HasConstraintName("FK__Umowa__ID_pracow__44CA3770");

            entity.HasOne(d => d.IdRodzajuNavigation).WithMany(p => p.Umowa)
                .HasForeignKey(d => d.IdRodzaju)
                .HasConstraintName("FK__Umowa__ID_rodzaj__45BE5BA9");
        });

        modelBuilder.Entity<Urlop>(entity =>
        {
            entity.HasKey(e => e.IdUrlopu).HasName("PK__Urlop__595D297155D937AC");

            entity.Property(e => e.IdUrlopu).HasColumnName("ID_urlopu");
            entity.Property(e => e.Nazwa)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<UrlopUmowa>(entity =>
        {
            entity.HasKey(e => e.IdUrlopUmowa).HasName("PK__Urlop_um__59C9C2FCC7CB2A66");

            entity.ToTable("Urlop_umowa");

            entity.Property(e => e.IdUrlopUmowa).HasColumnName("ID_Urlop_umowa");
            entity.Property(e => e.IdUmowy).HasColumnName("ID_umowy");
            entity.Property(e => e.IdUrlopu).HasColumnName("ID_urlopu");
            entity.Property(e => e.LiczbaDni)
                .HasColumnType("decimal(6, 2)")
                .HasColumnName("Liczba_dni");

            entity.HasOne(d => d.IdUmowyNavigation).WithMany(p => p.UrlopUmowa)
                .HasForeignKey(d => d.IdUmowy)
                .HasConstraintName("FK__Urlop_umo__ID_um__489AC854");

            entity.HasOne(d => d.IdUrlopuNavigation).WithMany(p => p.UrlopUmowa)
                .HasForeignKey(d => d.IdUrlopu)
                .HasConstraintName("FK__Urlop_umo__ID_ur__498EEC8D");
        });

        modelBuilder.Entity<Wlasciwosci>(entity =>
        {
            entity.HasKey(e => e.IdWlasciwosci).HasName("PK__Wlasciwo__BE19C1465B856696");

            entity.Property(e => e.IdWlasciwosci).HasColumnName("ID_wlasciwosci");
            entity.Property(e => e.IdJednostki).HasColumnName("ID_jednostki");
            entity.Property(e => e.NazwaParametru)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("Nazwa_parametru");

            entity.HasOne(d => d.IdJednostkiNavigation).WithMany(p => p.Wlasciwosci)
                .HasForeignKey(d => d.IdJednostki)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Wlasciwos__ID_je__02084FDA");
        });

        modelBuilder.Entity<WniosekUrlopowy>(entity =>
        {
            entity.HasKey(e => e.IdWniosku).HasName("PK__Wniosek___9D9F4BAF2098B19A");

            entity.ToTable("Wniosek_urlopowy");

            entity.Property(e => e.IdWniosku).HasColumnName("ID_wniosku");
            entity.Property(e => e.DataRozp).HasColumnName("Data_rozp");
            entity.Property(e => e.DataZak).HasColumnName("Data_zak");
            entity.Property(e => e.IdPracownik).HasColumnName("ID_pracownik");
            entity.Property(e => e.IdUrlopu).HasColumnName("ID_urlopu");
            entity.Property(e => e.StatusWniosku).HasColumnName("Status_wniosku");

            entity.HasOne(d => d.IdPracownikNavigation).WithMany(p => p.WniosekUrlopowy)
                .HasForeignKey(d => d.IdPracownik)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Wniosek_u__ID_pr__5441852A");

            entity.HasOne(d => d.IdUrlopuNavigation).WithMany(p => p.WniosekUrlopowy)
                .HasForeignKey(d => d.IdUrlopu)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Wniosek_u__ID_ur__5535A963");
        });

        modelBuilder.Entity<Wyposazenie>(entity =>
        {
            entity.HasKey(e => e.IdWyposazenie).HasName("PK__Wyposaze__39E58E71050F48D3");

            entity.Property(e => e.IdWyposazenie).HasColumnName("ID_wyposazenie");
            entity.Property(e => e.Nazwa)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Uwagi).HasMaxLength(250);
        });

        modelBuilder.Entity<WyposazenieWlasciwosci>(entity =>
        {
            entity.HasKey(e => e.IdWyposWlasc).HasName("PK__Wyposaze__9B217424C67499B6");

            entity.ToTable("Wyposazenie_wlasciwosci");

            entity.Property(e => e.IdWyposWlasc).HasColumnName("ID_wypos_wlasc");
            entity.Property(e => e.IdWlasciwosci).HasColumnName("ID_wlasciwosci");
            entity.Property(e => e.IdWyposazenie).HasColumnName("ID_wyposazenie");
            entity.Property(e => e.Wartosc).HasColumnType("decimal(6, 2)");

            entity.HasOne(d => d.IdWlasciwosciNavigation).WithMany(p => p.WyposazenieWlasciwosci)
                .HasForeignKey(d => d.IdWlasciwosci)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Wyposazen__ID_wl__2DE6D218");

            entity.HasOne(d => d.IdWyposazenieNavigation).WithMany(p => p.WyposazenieWlasciwosci)
                .HasForeignKey(d => d.IdWyposazenie)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Wyposazen__ID_wy__2EDAF651");
        });

        modelBuilder.Entity<Wysylka>(entity =>
        {
            entity.HasKey(e => e.IdWysylka).HasName("PK__Wysylka__ED56F2DA636A46F0");

            entity.Property(e => e.IdWysylka).HasColumnName("ID_wysylka");
            entity.Property(e => e.Cena).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.DataNadania).HasColumnName("Data_nadania");
        });

        modelBuilder.Entity<WysylkaZamowienie>(entity =>
        {
            entity.HasKey(e => e.WysylkaZamowienie1).HasName("PK__Wysylka___64CAF8F0EED0BA97");

            entity.ToTable("Wysylka_zamowienie");

            entity.Property(e => e.WysylkaZamowienie1).HasColumnName("Wysylka_zamowienie");
            entity.Property(e => e.IdWysylka).HasColumnName("ID_wysylka");
            entity.Property(e => e.IdZamowienie).HasColumnName("ID_zamowienie");

            entity.HasOne(d => d.IdWysylkaNavigation).WithMany(p => p.WysylkaZamowienie)
                .HasForeignKey(d => d.IdWysylka)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Wysylka_z__ID_wy__66603565");

            entity.HasOne(d => d.IdZamowienieNavigation).WithMany(p => p.WysylkaZamowienie)
                .HasForeignKey(d => d.IdZamowienie)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Wysylka_z__ID_za__656C112C");
        });

        modelBuilder.Entity<ZadanieProdukcyjne>(entity =>
        {
            entity.HasKey(e => e.IdZadanieP).HasName("PK__Zadanie___4024783428FC42B6");

            entity.ToTable("Zadanie_produkcyjne");

            entity.Property(e => e.IdZadanieP).HasColumnName("ID_zadanieP");
            entity.Property(e => e.DataZadania).HasColumnName("Data_zadania");
            entity.Property(e => e.IdMaszyna).HasColumnName("ID_maszyna");
            entity.Property(e => e.IdZamowienie).HasColumnName("ID_zamowienie");

            entity.HasOne(d => d.IdMaszynaNavigation).WithMany(p => p.ZadanieProdukcyjne)
                .HasForeignKey(d => d.IdMaszyna)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Zadanie_p__ID_ma__6B24EA82");

            entity.HasOne(d => d.IdZamowienieNavigation).WithMany(p => p.ZadanieProdukcyjne)
                .HasForeignKey(d => d.IdZamowienie)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Zadanie_p__ID_za__6C190EBB");
        });

        modelBuilder.Entity<Zamowienie>(entity =>
        {
            entity.HasKey(e => e.IdZamowienie).HasName("PK__Zamowien__7BF8C9EF981C1E04");

            entity.Property(e => e.IdZamowienie).HasColumnName("ID_zamowienie");
            entity.Property(e => e.DataPrzyjeciaZ).HasColumnName("Data_przyjecia_z");
            entity.Property(e => e.DataZrealizowaniaZ).HasColumnName("Data_zrealizowania_z");
            entity.Property(e => e.IdKlient).HasColumnName("ID_klient");

            entity.HasOne(d => d.IdKlientNavigation).WithMany(p => p.Zamowienie)
                .HasForeignKey(d => d.IdKlient)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Zamowieni__ID_kl__628FA481");
        });

        modelBuilder.Entity<ZwolnienieLekarskie>(entity =>
        {
            entity.HasKey(e => e.IdZwolnienie).HasName("PK__Zwolnien__3A67E027C3A934B3");

            entity.ToTable("Zwolnienie_lekarskie");

            entity.Property(e => e.IdZwolnienie).HasColumnName("ID_zwolnienie");
            entity.Property(e => e.DataKoniec).HasColumnName("Data_koniec");
            entity.Property(e => e.DataPoczatek).HasColumnName("Data_poczatek");
            entity.Property(e => e.IdPracownik).HasColumnName("ID_pracownik");
            entity.Property(e => e.IdTypZwolnienia).HasColumnName("ID_typ_zwolnienia");
            entity.Property(e => e.Uwagi).HasMaxLength(255);

            entity.HasOne(d => d.IdPracownikNavigation).WithMany(p => p.ZwolnienieLekarskie)
                .HasForeignKey(d => d.IdPracownik)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Zwolnieni__ID_pr__440B1D61");

            entity.HasOne(d => d.IdTypZwolnieniaNavigation).WithMany(p => p.ZwolnienieLekarskie)
                .HasForeignKey(d => d.IdTypZwolnienia)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Zwolnieni__ID_ty__44FF419A");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}