// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class PomiarMat
{
    public int IdPomiarMat { get; set; }

    public int IdKontrolaMat { get; set; }

    public int IdWlasciwosci { get; set; }

    public decimal WartoscZmierzona { get; set; }

    public virtual KontrolaMat IdKontrolaMatNavigation { get; set; }

    public virtual Wlasciwosci IdWlasciwosciNavigation { get; set; }
}