// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class Pomiar
{
    public int IdPomiar { get; set; }

    public int IdKontrolaProd { get; set; }

    public int? IdWlasciwosci { get; set; }

    public decimal WartoscZmierzona { get; set; }

    public virtual KontrolaProd IdKontrolaProdNavigation { get; set; }

    public virtual Wlasciwosci IdWlasciwosciNavigation { get; set; }
}