// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class Pracownik
{
    public int IdPracownik { get; set; }

    public int? IdOsoba { get; set; }

    public virtual ICollection<Awaria> Awaria { get; set; } = new List<Awaria>();

    public virtual ICollection<BadanieMedyczne> BadanieMedyczne { get; set; } = new List<BadanieMedyczne>();

    public virtual ICollection<Dostawa> Dostawa { get; set; } = new List<Dostawa>();

    public virtual Osoba IdOsobaNavigation { get; set; }

    public virtual ICollection<KontrolaMat> KontrolaMat { get; set; } = new List<KontrolaMat>();

    public virtual ICollection<KontrolaProd> KontrolaProd { get; set; } = new List<KontrolaProd>();

    public virtual ICollection<Obsluga> Obsluga { get; set; } = new List<Obsluga>();

    public virtual ICollection<PracownikSzkolenia> PracownikSzkolenia { get; set; } = new List<PracownikSzkolenia>();

    public virtual ICollection<Produkcja> Produkcja { get; set; } = new List<Produkcja>();

    public virtual ICollection<SiatkaPlac> SiatkaPlac { get; set; } = new List<SiatkaPlac>();

    public virtual ICollection<Umowa> Umowa { get; set; } = new List<Umowa>();

    public virtual ICollection<WniosekUrlopowy> WniosekUrlopowy { get; set; } = new List<WniosekUrlopowy>();

    public virtual ICollection<ZwolnienieLekarskie> ZwolnienieLekarskie { get; set; } = new List<ZwolnienieLekarskie>();
}