// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class PracownikSzkolenia
{
    public int IdPracownikSzkolenia { get; set; }

    public int IdPracownik { get; set; }

    public int IdSzkolenia { get; set; }

    public DateOnly DataSzkolenia { get; set; }

    public DateOnly? DataWaznosci { get; set; }

    public decimal CenaSzkolenia { get; set; }

    public virtual Pracownik IdPracownikNavigation { get; set; }

    public virtual Szkolenie IdSzkoleniaNavigation { get; set; }
}