// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class ProduktWlasciwosci
{
    public int IdProduktyWlasciwosci { get; set; }

    public int IdWlasciwosci { get; set; }

    public int IdProdukt { get; set; }

    public decimal WartoscMinimalna { get; set; }

    public decimal WartoscMaksymalna { get; set; }

    public virtual Produkt IdProduktNavigation { get; set; }

    public virtual Wlasciwosc IdWlasciwosciNavigation { get; set; }
}