// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class Produkcja
{
    public int IdProdukcja { get; set; }

    public int IdPracownik { get; set; }

    public decimal Rbh { get; set; }

    public decimal Wyprodukowano { get; set; }

    public decimal Odpady { get; set; }

    public int IdZadanieP { get; set; }

    public int IdNormyP { get; set; }

    public virtual NormaProd IdNormyPNavigation { get; set; }

    public virtual Pracownik IdPracownikNavigation { get; set; }

    public virtual ZadanieProdukcyjne IdZadaniePNavigation { get; set; }
}