// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class ProduktyNormy
{
    public int IdProduktyNormy { get; set; }

    public int IdNormy { get; set; }

    public int IdProdukt { get; set; }

    public virtual Normy IdNormyNavigation { get; set; }

    public virtual Produkty IdProduktNavigation { get; set; }
}