// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class Produkt
{
    public int IdProdukt { get; set; }

    public string Nazwa { get; set; }

    public virtual ICollection<NormaProd> NormaProd { get; set; } = new List<NormaProd>();

    public virtual ICollection<ProduktNorma> ProduktNorma { get; set; } = new List<ProduktNorma>();

    public virtual ICollection<ProduktWlasciwosci> ProduktWlasciwosci { get; set; } = new List<ProduktWlasciwosci>();

    public virtual ICollection<SzczegolyZamowienia> SzczegolyZamowienia { get; set; } = new List<SzczegolyZamowienia>();
}