// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class Produkty
{
    public int IdProdukt { get; set; }

    public string Nazwa { get; set; }

    public virtual ICollection<NormaProd> NormaProd { get; set; } = new List<NormaProd>();

    public virtual ICollection<ProduktyNormy> ProduktyNormy { get; set; } = new List<ProduktyNormy>();

    public virtual ICollection<ProduktyWlasciwosci> ProduktyWlasciwosci { get; set; } = new List<ProduktyWlasciwosci>();

    public virtual ICollection<SzczegolyZamowienia> SzczegolyZamowienia { get; set; } = new List<SzczegolyZamowienia>();
}