// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class RodzajUmowy
{
    public int IdRodzaju { get; set; }

    public string Nazwa { get; set; }

    public string Opis { get; set; }

    public virtual ICollection<Umowa> Umowa { get; set; } = new List<Umowa>();
}