// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class RodzajObslugi
{
    public int IdRodzajObslugi { get; set; }

    public string Nazwa { get; set; }

    public string Opis { get; set; }

    public virtual ICollection<Obsluga> Obsluga { get; set; } = new List<Obsluga>();
    public string DisplayText => $"{Nazwa} - {Opis}";
}