// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class RodzajMaterialu
{
    public int IdRodzaj { get; set; }

    public string Nazwa { get; set; }

    public virtual ICollection<SzczegolyDostawy> SzczegolyDostawy { get; set; } = new List<SzczegolyDostawy>();
}