// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class SiatkaPlac
{
    public int IdSiatkaPlac { get; set; }

    public DateOnly DataPocz { get; set; }

    public DateOnly? DataKoniec { get; set; }

    public int IdPracownik { get; set; }

    public decimal Wynagrodzenie { get; set; }

    public virtual Pracownik IdPracownikNavigation { get; set; }
}