// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class SzczegolyDostawy
{
    public int IdSzczegolyDostawy { get; set; }

    public int IdDostawa { get; set; }

    public int IdMaterial { get; set; }

    public decimal Liczba { get; set; }

    public decimal Cena { get; set; }

    public virtual Dostawa IdDostawaNavigation { get; set; }

    public virtual Material IdMaterialNavigation { get; set; }
}