// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class SzczegolyZamowienia
{
    public int IdSzczegolyZamowienia { get; set; }

    public int IdZamowienie { get; set; }

    public int IdProdukt { get; set; }

    public decimal Ilosc { get; set; }

    public int IdMaterial { get; set; }

    public string Uwagi { get; set; }

    public decimal Cena { get; set; }

    public virtual Material IdMaterialNavigation { get; set; }

    public virtual Produkt IdProduktNavigation { get; set; }

    public virtual Zamowienie IdZamowienieNavigation { get; set; }
}