// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class Szkolenie
{
    public int IdSzkolenia { get; set; }

    public string Nazwa { get; set; }

    public string Opis { get; set; }

    public bool? CzyObowiazkowe { get; set; }

    public DateOnly? Waznosc { get; set; }

    public virtual ICollection<PracownikSzkolenia> PracownikSzkolenia { get; set; } = new List<PracownikSzkolenia>();
}
