// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class Typ
{
    public int IdTyp { get; set; }

    public string Nazwa { get; set; }

    public virtual ICollection<MaszynaTyp> MaszynaTyp { get; set; } = new List<MaszynaTyp>();

    public virtual ICollection<TypWlasciwosci> TypWlasciwosci { get; set; } = new List<TypWlasciwosci>();
}