// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class TypBadaniaMed
{
    public int IdTypBadaniaMed { get; set; }

    public string Nazwa { get; set; }

    public string Opis { get; set; }

    public virtual ICollection<BadanieMedyczne> BadanieMedyczne { get; set; } = new List<BadanieMedyczne>();
}