// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class TypWlasciwosci
{
    public int IdTypWlasciwosci { get; set; }

    public int IdWlasciwosci { get; set; }

    public int IdTyp { get; set; }

    public decimal Wartosc { get; set; }

    public virtual Typ IdTypNavigation { get; set; }

    public virtual Wlasciwosc IdWlasciwosciNavigation { get; set; }
}