// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class Umowa
{
    public int IdUmowa { get; set; }

    public int? IdPracownik { get; set; }

    public DateOnly DataRoz { get; set; }

    public DateOnly DataZak { get; set; }

    public int? IdRodzaju { get; set; }

    public virtual Pracownik IdPracownikNavigation { get; set; }

    public virtual RodzajUmowy IdRodzajuNavigation { get; set; }

    public virtual ICollection<UrlopUmowa> UrlopUmowa { get; set; } = new List<UrlopUmowa>();
}