// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class UrlopUmowa
{
    public int IdUrlopUmowa { get; set; }

    public int? IdUmowy { get; set; }

    public int? IdUrlopu { get; set; }

    public decimal LiczbaDni { get; set; }

    public virtual Umowa IdUmowyNavigation { get; set; }

    public virtual Urlop IdUrlopuNavigation { get; set; }
}