// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class Urlop
{
    public int IdUrlopu { get; set; }

    public string Nazwa { get; set; }

    public virtual ICollection<UrlopUmowa> UrlopUmowa { get; set; } = new List<UrlopUmowa>();

    public virtual ICollection<WniosekUrlopowy> WniosekUrlopowy { get; set; } = new List<WniosekUrlopowy>();
}