// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class WidokPracownikZadaniaProdukcyjne
{
    public int IdPracownik { get; set; }

    public string Imie { get; set; }

    public string Nazwisko { get; set; }

    public DateOnly DataZadania { get; set; }
}