// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class WidokProdukcjaProcentRealizacji
{
    public int IdZamowienie { get; set; }

    public decimal? SredniaWartoscFormula { get; set; }
}