// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class WidokSumaRbhMaszyna
{
    public DateOnly Data { get; set; }

    public int IdMaszyna { get; set; }

    public decimal? SumaRbh { get; set; }
}