// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class WidokZamowieniaZadania
{
    public int IdZamowienie { get; set; }

    public int IdProdukcja { get; set; }

    public DateOnly DataZadania { get; set; }

    public string NazwaMaszyny { get; set; }

    public string Pracownik { get; set; }

    public decimal Rbh { get; set; }

    public string NazwaProduktu { get; set; }

    public decimal? ObliczonaIloscWyprodukowana { get; set; }

    public decimal? ObliczonaIloscOdpadow { get; set; }
}