// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class WidokWszystkieMaszynyRbh
{
    public int IdMaszyna { get; set; }

    public string NazwaMaszyny { get; set; }

    public DateOnly? DataPracy { get; set; }

    public decimal SumaRbh { get; set; }
}