// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class WidokProdukcjaZestawienieEfektow
{
    public int IdZamowienie { get; set; }

    public decimal? OczekiwaneZuzycieMaterialu { get; set; }

    public decimal? OczekiwanaProdukcja { get; set; }

    public decimal? OczekiwaneOdpady { get; set; }

    public decimal? RealneZuzycieMaterialu { get; set; }

    public decimal? RealnaProdukcja { get; set; }

    public decimal? RealneOdpady { get; set; }
}