// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class WidokProdukcjaRealizacjaObliczenia
{
    public int IdZamowienie { get; set; }

    public string NazwaProduktu { get; set; }

    public decimal? IloscZamowienia { get; set; }

    public decimal? SumaOdpady { get; set; }

    public decimal? SumaWyprodukowano { get; set; }

    public decimal? WartoscFormula { get; set; }
}