// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class WidokZamowienieZadanieProdukcja
{
    public int IdZamowienie { get; set; }

    public int IdZadanieP { get; set; }

    public DateOnly DataZadania { get; set; }

    public int IdProdukcja { get; set; }

    public decimal? Wyprodukowano { get; set; }

    public decimal? Odpady { get; set; }
}