// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class WidokProdukcjaPlanowanieObliczenia
{
    public int IdZamowienie { get; set; }

    public string NazwaProduktu { get; set; }

    public decimal IloscZamowienia { get; set; }

    public decimal? SumaOdpady { get; set; }

    public decimal? ZaplanowanaProdukcja { get; set; }

    public decimal? ProcentZaplanowanejProdukcji { get; set; }
}