// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class Wlasciwosci
{
    public int IdWlasciwosci { get; set; }

    public string NazwaParametru { get; set; }

    public int IdJednostki { get; set; }

    public virtual Jednostki IdJednostkiNavigation { get; set; }

    public virtual ICollection<MaterialWlasciwosci> MaterialWlasciwosci { get; set; } = new List<MaterialWlasciwosci>();

    public virtual ICollection<Pomiar> Pomiar { get; set; } = new List<Pomiar>();

    public virtual ICollection<PomiarMat> PomiarMat { get; set; } = new List<PomiarMat>();

    public virtual ICollection<ProduktyWlasciwosci> ProduktyWlasciwosci { get; set; } = new List<ProduktyWlasciwosci>();

    public virtual ICollection<TypWlasciwosci> TypWlasciwosci { get; set; } = new List<TypWlasciwosci>();

    public virtual ICollection<WyposazenieWlasciwosci> WyposazenieWlasciwosci { get; set; } = new List<WyposazenieWlasciwosci>();
}