// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class WniosekUrlopowy
{
    public int IdWniosku { get; set; }

    public int IdPracownik { get; set; }

    public DateOnly DataRozp { get; set; }

    public DateOnly DataZak { get; set; }

    public int IdUrlopu { get; set; }

    public bool StatusWniosku { get; set; }

    public virtual Pracownik IdPracownikNavigation { get; set; }

    public virtual Urlop IdUrlopuNavigation { get; set; }
}