// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class WyposazenieWlasciwosci
{
    public int IdWyposWlasc { get; set; }

    public int IdWlasciwosci { get; set; }

    public int IdWyposazenie { get; set; }

    public decimal Wartosc { get; set; }

    public virtual Wlasciwosci IdWlasciwosciNavigation { get; set; }

    public virtual Wyposazenie IdWyposazenieNavigation { get; set; }
}