// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class Wyposazenie
{
    public int IdWyposazenie { get; set; }

    public string Nazwa { get; set; }

    public string Uwagi { get; set; }

    public virtual ICollection<MaszynaWyp> MaszynaWyp { get; set; } = new List<MaszynaWyp>();

    public virtual ICollection<WyposazenieWlasciwosci> WyposazenieWlasciwosci { get; set; } = new List<WyposazenieWlasciwosci>();
}