// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class WysylkaZamowienie
{
    public int WysylkaZamowienie1 { get; set; }

    public int IdZamowienie { get; set; }

    public int IdWysylka { get; set; }

    public virtual Wysylka IdWysylkaNavigation { get; set; }

    public virtual Zamowienie IdZamowienieNavigation { get; set; }
}