// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class Wysylka
{
    public int IdWysylka { get; set; }

    public DateOnly DataNadania { get; set; }

    public decimal Cena { get; set; }

    public virtual ICollection<WysylkaZamowienie> WysylkaZamowienie { get; set; } = new List<WysylkaZamowienie>();
}