// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class ZadanieProdukcyjne
{
    public int IdZadanieP { get; set; }

    public int IdMaszyna { get; set; }

    public DateOnly DataZadania { get; set; }

    public int IdZamowienie { get; set; }

    public virtual Maszyna IdMaszynaNavigation { get; set; }

    public virtual Zamowienie IdZamowienieNavigation { get; set; }

    public virtual ICollection<KontrolaMat> KontrolaMat { get; set; } = new List<KontrolaMat>();

    public virtual ICollection<KontrolaProd> KontrolaProd { get; set; } = new List<KontrolaProd>();

    public virtual ICollection<Produkcja> Produkcja { get; set; } = new List<Produkcja>();
}