// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class Zamowienie
{
    public int IdZamowienie { get; set; }

    public int IdKlient { get; set; }

    public DateOnly DataPrzyjeciaZ { get; set; }

    public DateOnly? DataZrealizowaniaZ { get; set; }

    public virtual Klient IdKlientNavigation { get; set; }

    public virtual ICollection<SzczegolyZamowienia> SzczegolyZamowienia { get; set; } = new List<SzczegolyZamowienia>();

    public virtual ICollection<WysylkaZamowienie> WysylkaZamowienie { get; set; } = new List<WysylkaZamowienie>();

    public virtual ICollection<ZadanieProdukcyjne> ZadanieProdukcyjne { get; set; } = new List<ZadanieProdukcyjne>();
}