// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodkladexApp.Models;

public partial class ZwolnienieLekarskie
{
    public int IdZwolnienie { get; set; }

    public int IdPracownik { get; set; }

    public int IdTypZwolnienia { get; set; }

    public DateOnly DataPoczatek { get; set; }

    public DateOnly DataKoniec { get; set; }

    public string Uwagi { get; set; }

    public virtual Pracownik IdPracownikNavigation { get; set; }

    public virtual TypZwolnienie IdTypZwolnieniaNavigation { get; set; }
}